/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package com.zing.zingsorestiers.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;

import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.Block;

import com.zing.zingsorestiers.block.*;
import com.zing.zingsorestiers.ZingsOresAndTiersMod;

import java.util.function.Function;

public class ZingsOresAndTiersModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(ZingsOresAndTiersMod.MODID);
	public static final DeferredBlock<Block> RESIN_BULB_LIT;
	public static final DeferredBlock<Block> RESIN_BULB;
	public static final DeferredBlock<Block> RESIN_LANTERN;
	public static final DeferredBlock<Block> RESIN_TORCH;
	public static final DeferredBlock<Block> GOLDEN_LANTERN;
	public static final DeferredBlock<Block> GOLDEN_TORCH;
	public static final DeferredBlock<Block> IRON_LANTERN;
	public static final DeferredBlock<Block> IRON_TORCH;
	public static final DeferredBlock<Block> NETHERITE_LANTERN;
	public static final DeferredBlock<Block> NETHERITE_TORCH;
	public static final DeferredBlock<Block> WARPED_NETHERITE_LANTERN;
	public static final DeferredBlock<Block> WARPED_NETHERITE_TORCH;
	public static final DeferredBlock<Block> CRIMSON_NETHERITE_LANTERN;
	public static final DeferredBlock<Block> CRIMSON_NETHERITE_TORCH;
	public static final DeferredBlock<Block> NETHERITE_LIGHTNING_ROD;
	public static final DeferredBlock<Block> GOLDEN_LIGHTNING_ROD;
	public static final DeferredBlock<Block> IRON_LIGHTNING_ROD;
	public static final DeferredBlock<Block> NETHERITE_CHAIN;
	public static final DeferredBlock<Block> GOLDEN_CHAIN;
	public static final DeferredBlock<Block> NETHERITE_BULB;
	public static final DeferredBlock<Block> CRIMSON_NETHERITE_BULB;
	public static final DeferredBlock<Block> WARPED_NETHERITE_BULB;
	public static final DeferredBlock<Block> NETHERITE_BULB_LIT;
	public static final DeferredBlock<Block> CRIMSON_NETHERITE_BULB_LIT;
	public static final DeferredBlock<Block> WARPED_NETHERITE_BULB_LIT;
	public static final DeferredBlock<Block> BOLTED_NETHERITE;
	public static final DeferredBlock<Block> NETHERITE_RAIL;
	public static final DeferredBlock<Block> NETHERITE_TRAPDOOR;
	public static final DeferredBlock<Block> NETHERITE_GRATE;
	public static final DeferredBlock<Block> CUT_NETHERITE;
	public static final DeferredBlock<Block> CUT_NETHERITE_STAIRS;
	public static final DeferredBlock<Block> CUT_NETHERITE_SLAB;
	public static final DeferredBlock<Block> NETHERITE_BARS;
	public static final DeferredBlock<Block> NETHERITE_DOOR;
	public static final DeferredBlock<Block> CUT_IRON;
	public static final DeferredBlock<Block> BOLTED_IRON;
	public static final DeferredBlock<Block> CUT_GOLD;
	public static final DeferredBlock<Block> BOLTED_GOLD;
	public static final DeferredBlock<Block> GOLDEN_BARS;
	public static final DeferredBlock<Block> GOLDEN_TRAPDOOR;
	public static final DeferredBlock<Block> GOLDEN_DOOR;
	public static final DeferredBlock<Block> GOLDEN_GRATE;
	public static final DeferredBlock<Block> IRON_GRATE;
	public static final DeferredBlock<Block> COPPER_RAIL;
	public static final DeferredBlock<Block> GOLDEN_RAIL;
	public static final DeferredBlock<Block> GOLDEN_BULB;
	public static final DeferredBlock<Block> IRON_BULB;
	public static final DeferredBlock<Block> IRON_BULB_LIT;
	public static final DeferredBlock<Block> GOLDEN_BULB_LIT;
	public static final DeferredBlock<Block> AMETHYST_ORE;
	public static final DeferredBlock<Block> RESIN_ORE;
	public static final DeferredBlock<Block> QUARTZ_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_QUARTZ_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_AMETHYST_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_RESIN_ORE;
	public static final DeferredBlock<Block> ANDESITE_AMETHYST_ORE;
	public static final DeferredBlock<Block> DIORITE_AMETHYST_ORE;
	public static final DeferredBlock<Block> GRANITE_AMETHYST_ORE;
	public static final DeferredBlock<Block> TUFF_AMETHYST_ORE;
	public static final DeferredBlock<Block> ANDESITE_RESIN_ORE;
	public static final DeferredBlock<Block> DIORITE_RESIN_ORE;
	public static final DeferredBlock<Block> GRANITE_RESIN_ORE;
	public static final DeferredBlock<Block> TUFF_RESIN_ORE;
	public static final DeferredBlock<Block> ANDESITE_QUARTZ_ORE;
	public static final DeferredBlock<Block> DIORITE_QUARTZ_ORE;
	public static final DeferredBlock<Block> GRANITE_QUARTZ_ORE;
	public static final DeferredBlock<Block> TUFF_QUARTZ_ORE;
	public static final DeferredBlock<Block> CLAY_AMETHYST_ORE;
	public static final DeferredBlock<Block> CALCITE_AMETHYST_ORE;
	public static final DeferredBlock<Block> BASALT_AMETHYST_ORE;
	public static final DeferredBlock<Block> PALE_MOSS_RESIN_ORE;
	public static final DeferredBlock<Block> BASALT_QUARTZ_ORE;
	public static final DeferredBlock<Block> ANDESITE_DIAMOND_ORE;
	public static final DeferredBlock<Block> ANDESITE_COAL_ORE;
	public static final DeferredBlock<Block> ANDESITE_REDSTONE_ORE;
	public static final DeferredBlock<Block> ANDESITE_EMERALD_ORE;
	public static final DeferredBlock<Block> ANDESITE_GOLD_ORE;
	public static final DeferredBlock<Block> ANDESITE_IRON_ORE;
	public static final DeferredBlock<Block> ANDESITE_LAPIS_LAZULI_ORE;
	public static final DeferredBlock<Block> ANDESITE_COPPER_ORE;
	public static final DeferredBlock<Block> DIORITE_DIAMOND_ORE;
	public static final DeferredBlock<Block> GRANITE_DIAMOND_ORE;
	public static final DeferredBlock<Block> OBSIDIAN_DIAMOND_ORE;
	public static final DeferredBlock<Block> TUFF_DIAMOND_ORE;
	public static final DeferredBlock<Block> SANDSTONE_DIAMOND_ORE;
	public static final DeferredBlock<Block> DIORITE_EMERALD_ORE;
	public static final DeferredBlock<Block> GRANITE_EMERALD_ORE;
	public static final DeferredBlock<Block> TUFF_EMERALD_ORE;
	public static final DeferredBlock<Block> SANDSTONE_EMERALD_ORE;
	public static final DeferredBlock<Block> GRANITE_COAL_ORE;
	public static final DeferredBlock<Block> DIORITE_COAL_ORE;
	public static final DeferredBlock<Block> TUFF_COAL_ORE;
	public static final DeferredBlock<Block> SANDSTONE_COAL_ORE;
	public static final DeferredBlock<Block> DIORITE_GOLD_ORE;
	public static final DeferredBlock<Block> GRANITE_GOLD_ORE;
	public static final DeferredBlock<Block> TUFF_GOLD_ORE;
	public static final DeferredBlock<Block> SANDSTONE_GOLD_ORE;
	public static final DeferredBlock<Block> TERRACOTTA_GOLD_ORE;
	public static final DeferredBlock<Block> BASALT_GOLD_ORE;
	public static final DeferredBlock<Block> RED_SANDSTONE_GOLD_ORE;
	public static final DeferredBlock<Block> TUFF_IRON_ORE;
	public static final DeferredBlock<Block> SANDSTONE_IRON_ORE;
	public static final DeferredBlock<Block> GRANITE_IRON_ORE;
	public static final DeferredBlock<Block> DIORITE_IRON_ORE;
	public static final DeferredBlock<Block> DIORITE_COPPER_ORE;
	public static final DeferredBlock<Block> GRANITE_COPPER_ORE;
	public static final DeferredBlock<Block> TUFF_COPPER_ORE;
	public static final DeferredBlock<Block> DRIPSTONE_COPPER_ORE;
	public static final DeferredBlock<Block> DIORITE_REDSTONE_ORE;
	public static final DeferredBlock<Block> GRANITE_REDSTONE_ORE;
	public static final DeferredBlock<Block> SANDSTONE_REDSTONE_ORE;
	public static final DeferredBlock<Block> TUFF_REDSTONE_ORE;
	public static final DeferredBlock<Block> DIORITE_LAPIS_LAZULI_ORE;
	public static final DeferredBlock<Block> GRANITE_LAPIS_LAZULI_ORE;
	public static final DeferredBlock<Block> SANDSTONE_LAPIS_LAZULI_ORE;
	public static final DeferredBlock<Block> TUFF_LAPIS_LAZULI_ORE;
	public static final DeferredBlock<Block> COPPER_DANDELION;
	public static final DeferredBlock<Block> NETHERITE_DANDELION;
	public static final DeferredBlock<Block> IRON_DANDELION;
	public static final DeferredBlock<Block> DIAMOND_DANDELION;
	public static final DeferredBlock<Block> EMERALD_WALL;
	public static final DeferredBlock<Block> EMERALD_SLAB;
	public static final DeferredBlock<Block> EMERALD_STAIRS;
	public static final DeferredBlock<Block> COAL_WALL;
	public static final DeferredBlock<Block> COAL_STAIRS;
	public static final DeferredBlock<Block> COAL_SLAB;
	public static final DeferredBlock<Block> DIRT_COAL_ORE;
	public static final DeferredBlock<Block> DIRT_GOLD_ORE;
	public static final DeferredBlock<Block> DIRT_RESIN_ORE;
	public static final DeferredBlock<Block> BURNT_OUT_TORCH;
	public static final DeferredBlock<Block> BLOCK_OF_BURNING_COAL;
	public static final DeferredBlock<Block> BLOCK_OF_CHARCOAL;
	public static final DeferredBlock<Block> POWDERED_GOLD;
	public static final DeferredBlock<Block> CLUMPED_GOLD;
	public static final DeferredBlock<Block> METALLIC_GOLD;
	public static final DeferredBlock<Block> BEVELED_GOLD;
	public static final DeferredBlock<Block> ROUGH_GOLD;
	public static final DeferredBlock<Block> SPECKLED_GOLD;
	public static final DeferredBlock<Block> CLEAR_GOLD;
	public static final DeferredBlock<Block> STONY_GOLD;
	public static final DeferredBlock<Block> CRYSTALIZED_GOLD;
	public static final DeferredBlock<Block> BOLTED_EMERALD;
	public static final DeferredBlock<Block> POWDERED_EMERALD;
	public static final DeferredBlock<Block> CLUMPED_EMERALD;
	public static final DeferredBlock<Block> METALLIC_EMERALD;
	public static final DeferredBlock<Block> GLOSSY_EMERALD;
	public static final DeferredBlock<Block> ROUGH_EMERALD;
	public static final DeferredBlock<Block> SPECKLED_EMERALD;
	public static final DeferredBlock<Block> CLEAR_EMERALD;
	public static final DeferredBlock<Block> STONY_EMERALD;
	public static final DeferredBlock<Block> CRYSTALIZED_EMERALD;
	public static final DeferredBlock<Block> BEVELED_AMETHYST;
	public static final DeferredBlock<Block> BOLTED_AMETHYST;
	public static final DeferredBlock<Block> POWDERED_AMETHYST;
	public static final DeferredBlock<Block> CLUMPED_AMETHYST;
	public static final DeferredBlock<Block> METALLIC_AMETHYST;
	public static final DeferredBlock<Block> GLOSSY_AMETHYST;
	public static final DeferredBlock<Block> ROUGH_AMETHYST;
	public static final DeferredBlock<Block> SPECKLED_AMETHYST;
	public static final DeferredBlock<Block> CLEAR_AMETHYST;
	public static final DeferredBlock<Block> STONY_AMETHYST;
	public static final DeferredBlock<Block> BEVELED_QUARTZ;
	public static final DeferredBlock<Block> BOLTED_QUARTZ;
	public static final DeferredBlock<Block> POWDERED_QUARTZ;
	public static final DeferredBlock<Block> CLUMPED_QUARTZ;
	public static final DeferredBlock<Block> METALLIC_QUARTZ;
	public static final DeferredBlock<Block> GLOSSY_QUARTZ;
	public static final DeferredBlock<Block> ROUGH_QUARTZ;
	public static final DeferredBlock<Block> SPECKLED_QUARTZ;
	public static final DeferredBlock<Block> STONY_QUARTZ;
	public static final DeferredBlock<Block> CRYSTALIZED_QUARTZ;
	public static final DeferredBlock<Block> BEVELED_RESIN;
	public static final DeferredBlock<Block> BOLTED_RESIN;
	public static final DeferredBlock<Block> POWDERED_RESIN;
	public static final DeferredBlock<Block> METALLIC_RESIN;
	public static final DeferredBlock<Block> GLOSSY_RESIN;
	public static final DeferredBlock<Block> ROUGH_RESIN;
	public static final DeferredBlock<Block> SPECKLED_RESIN;
	public static final DeferredBlock<Block> CLEAR_RESIN;
	public static final DeferredBlock<Block> STONY_RESIN;
	public static final DeferredBlock<Block> CRYSTALIZED_RESIN;
	public static final DeferredBlock<Block> TOUGH_COAL;
	public static final DeferredBlock<Block> BEVELED_COAL;
	public static final DeferredBlock<Block> BOLTED_COAL;
	public static final DeferredBlock<Block> POWDERED_COAL;
	public static final DeferredBlock<Block> METALLIC_COAL;
	public static final DeferredBlock<Block> GLOSSY_COAL;
	public static final DeferredBlock<Block> SPECKLED_COAL;
	public static final DeferredBlock<Block> CLUMPED_COAL;
	public static final DeferredBlock<Block> CLEAR_COAL;
	public static final DeferredBlock<Block> CRYSTALIZED_COAL;
	public static final DeferredBlock<Block> TOUGH_LAPIS_LAZULI;
	public static final DeferredBlock<Block> BEVELED_LAPIS_LAZULI;
	public static final DeferredBlock<Block> BOLTED_LAPIS_LAZULI;
	public static final DeferredBlock<Block> POWDERED_LAPIS_LAZULI;
	public static final DeferredBlock<Block> METALLIC_LAPIS_LAZULI;
	public static final DeferredBlock<Block> GLOSSY_LAPIS_LAZULI;
	public static final DeferredBlock<Block> STONY_LAPIS_LAZULI;
	public static final DeferredBlock<Block> CLUMPED_LAPIS_LAZULI;
	public static final DeferredBlock<Block> CLEAR_LAPIS_LAZULI;
	public static final DeferredBlock<Block> CRYSTALIZED_LAPIS_LAZULI;
	public static final DeferredBlock<Block> TOUGH_REDSTONE;
	public static final DeferredBlock<Block> BEVELED_REDSTONE;
	public static final DeferredBlock<Block> BOLTED_REDSTONE;
	public static final DeferredBlock<Block> SPECKLED_REDSTONE;
	public static final DeferredBlock<Block> METALLIC_REDSTONE;
	public static final DeferredBlock<Block> GLOSSY_REDSTONE;
	public static final DeferredBlock<Block> STONY_REDSTONE;
	public static final DeferredBlock<Block> CLUMPED_REDSTONE;
	public static final DeferredBlock<Block> CLEAR_REDSTONE;
	public static final DeferredBlock<Block> CRYSTALIZED_REDSTONE;
	public static final DeferredBlock<Block> TOUGH_COPPER;
	public static final DeferredBlock<Block> BEVELED_COPPER;
	public static final DeferredBlock<Block> POWDERED_COPPER;
	public static final DeferredBlock<Block> SPECKLED_COPPER;
	public static final DeferredBlock<Block> METALLIC_COPPER;
	public static final DeferredBlock<Block> GLOSSY_COPPER;
	public static final DeferredBlock<Block> STONY_COPPER;
	public static final DeferredBlock<Block> CLUMPED_COPPER;
	public static final DeferredBlock<Block> CLEAR_COPPER;
	public static final DeferredBlock<Block> CRYSTALIZED_COPPER;
	public static final DeferredBlock<Block> TOUGH_IRON;
	public static final DeferredBlock<Block> BEVELED_IRON;
	public static final DeferredBlock<Block> POWDERED_IRON;
	public static final DeferredBlock<Block> SPECKLED_IRON;
	public static final DeferredBlock<Block> GLOSSY_IRON;
	public static final DeferredBlock<Block> STONY_IRON;
	public static final DeferredBlock<Block> CLUMPED_IRON;
	public static final DeferredBlock<Block> CLEAR_IRON;
	public static final DeferredBlock<Block> CRYSTALIZED_IRON;
	public static final DeferredBlock<Block> METALLIC_NETHERITE;
	public static final DeferredBlock<Block> BEVELED_NETHERITE;
	public static final DeferredBlock<Block> POWDERED_NETHERITE;
	public static final DeferredBlock<Block> SPECKLED_NETHERITE;
	public static final DeferredBlock<Block> GLOSSY_NETHERITE;
	public static final DeferredBlock<Block> STONY_NETHERITE;
	public static final DeferredBlock<Block> CLUMPED_NETHERITE;
	public static final DeferredBlock<Block> CLEAR_NETHERITE;
	public static final DeferredBlock<Block> CRYSTALIZED_NETHERITE;
	public static final DeferredBlock<Block> TOUGH_DIAMOND;
	public static final DeferredBlock<Block> METALLIC_DIAMOND;
	public static final DeferredBlock<Block> BEVELED_DIAMOND;
	public static final DeferredBlock<Block> POWDERED_DIAMOND;
	public static final DeferredBlock<Block> SPECKLED_DIAMOND;
	public static final DeferredBlock<Block> BOLTED_DIAMOND;
	public static final DeferredBlock<Block> STONY_DIAMOND;
	public static final DeferredBlock<Block> CLUMPED_DIAMOND;
	public static final DeferredBlock<Block> CLEAR_DIAMOND;
	public static final DeferredBlock<Block> CRYSTALIZED_DIAMOND;
	public static final DeferredBlock<Block> BASALT_NETHERITE_ORE;
	public static final DeferredBlock<Block> BONE_BLOCK_NETHERITE_ORE;
	public static final DeferredBlock<Block> COPPER_CAMPFIRE;
	public static final DeferredBlock<Block> PRISMARINE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_PRISMARINE_ORE;
	public static final DeferredBlock<Block> BEVELED_PRISMARINE;
	public static final DeferredBlock<Block> CLUMPED_PRISMARINE;
	public static final DeferredBlock<Block> CLEAR_PRISMARINE;
	public static final DeferredBlock<Block> CRYSTALIZED_PRISMARINE;
	public static final DeferredBlock<Block> BOLTED_PRISMARINE;
	public static final DeferredBlock<Block> STONY_PRISMARINE;
	public static final DeferredBlock<Block> ROUGH_PRISMARINE;
	public static final DeferredBlock<Block> METALLIC_PRISMARINE;
	public static final DeferredBlock<Block> GLOSSY_PRISMARINE;
	public static final DeferredBlock<Block> POWDERED_PRISMARINE;
	public static final DeferredBlock<Block> SPECKLED_PRISMARINE;
	public static final DeferredBlock<Block> HUE_AMETHYST;
	public static final DeferredBlock<Block> HUE_COAL;
	public static final DeferredBlock<Block> HUE_COPPER;
	public static final DeferredBlock<Block> HUE_DIAMOND;
	public static final DeferredBlock<Block> HUE_EMERALD;
	public static final DeferredBlock<Block> HUE_GOLD;
	public static final DeferredBlock<Block> HUE_IRON;
	public static final DeferredBlock<Block> HUE_LAPIS_LAZULI;
	public static final DeferredBlock<Block> HUE_NETHERITE;
	public static final DeferredBlock<Block> HUE_QUARTZ;
	public static final DeferredBlock<Block> HUE_REDSTONE;
	public static final DeferredBlock<Block> HUE_RESIN;
	public static final DeferredBlock<Block> MYSTERY_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_MYSTERY_ORE;
	static {
		RESIN_BULB_LIT = register("resin_bulb_lit", ResinBulbLitBlock::new);
		RESIN_BULB = register("resin_bulb", ResinBulbBlock::new);
		RESIN_LANTERN = register("resin_lantern", ResinLanternBlock::new);
		RESIN_TORCH = register("resin_torch", ResinTorchBlock::new);
		GOLDEN_LANTERN = register("golden_lantern", GoldenLanternBlock::new);
		GOLDEN_TORCH = register("golden_torch", GoldenTorchBlock::new);
		IRON_LANTERN = register("iron_lantern", IronLanternBlock::new);
		IRON_TORCH = register("iron_torch", IronTorchBlock::new);
		NETHERITE_LANTERN = register("netherite_lantern", NetheriteLanternBlock::new);
		NETHERITE_TORCH = register("netherite_torch", NetheriteTorchBlock::new);
		WARPED_NETHERITE_LANTERN = register("warped_netherite_lantern", WarpedNetheriteLanternBlock::new);
		WARPED_NETHERITE_TORCH = register("warped_netherite_torch", WarpedNetheriteTorchBlock::new);
		CRIMSON_NETHERITE_LANTERN = register("crimson_netherite_lantern", CrimsonNetheriteLanternBlock::new);
		CRIMSON_NETHERITE_TORCH = register("crimson_netherite_torch", CrimsonNetheriteTorchBlock::new);
		NETHERITE_LIGHTNING_ROD = register("netherite_lightning_rod", NetheriteLightningRodBlock::new);
		GOLDEN_LIGHTNING_ROD = register("golden_lightning_rod", GoldenLightningRodBlock::new);
		IRON_LIGHTNING_ROD = register("iron_lightning_rod", IronLightningRodBlock::new);
		NETHERITE_CHAIN = register("netherite_chain", NetheriteChainBlock::new);
		GOLDEN_CHAIN = register("golden_chain", GoldenChainBlock::new);
		NETHERITE_BULB = register("netherite_bulb", NetheriteBulbBlock::new);
		CRIMSON_NETHERITE_BULB = register("crimson_netherite_bulb", CrimsonNetheriteBulbBlock::new);
		WARPED_NETHERITE_BULB = register("warped_netherite_bulb", WarpedNetheriteBulbBlock::new);
		NETHERITE_BULB_LIT = register("netherite_bulb_lit", NetheriteBulbLitBlock::new);
		CRIMSON_NETHERITE_BULB_LIT = register("crimson_netherite_bulb_lit", CrimsonNetheriteBulbLitBlock::new);
		WARPED_NETHERITE_BULB_LIT = register("warped_netherite_bulb_lit", WarpedNetheriteBulbLitBlock::new);
		BOLTED_NETHERITE = register("bolted_netherite", BoltedNetheriteBlock::new);
		NETHERITE_RAIL = register("netherite_rail", NetheriteRailBlock::new);
		NETHERITE_TRAPDOOR = register("netherite_trapdoor", NetheriteTrapdoorBlock::new);
		NETHERITE_GRATE = register("netherite_grate", NetheriteGrateBlock::new);
		CUT_NETHERITE = register("cut_netherite", CutNetheriteBlock::new);
		CUT_NETHERITE_STAIRS = register("cut_netherite_stairs", CutNetheriteStairsBlock::new);
		CUT_NETHERITE_SLAB = register("cut_netherite_slab", CutNetheriteSlabBlock::new);
		NETHERITE_BARS = register("netherite_bars", NetheriteBarsBlock::new);
		NETHERITE_DOOR = register("netherite_door", NetheriteDoorBlock::new);
		CUT_IRON = register("cut_iron", CutIronBlock::new);
		BOLTED_IRON = register("bolted_iron", BoltedIronBlock::new);
		CUT_GOLD = register("cut_gold", CutGoldBlock::new);
		BOLTED_GOLD = register("bolted_gold", BoltedGoldBlock::new);
		GOLDEN_BARS = register("golden_bars", GoldenBarsBlock::new);
		GOLDEN_TRAPDOOR = register("golden_trapdoor", GoldenTrapdoorBlock::new);
		GOLDEN_DOOR = register("golden_door", GoldenDoorBlock::new);
		GOLDEN_GRATE = register("golden_grate", GoldenGrateBlock::new);
		IRON_GRATE = register("iron_grate", IronGrateBlock::new);
		COPPER_RAIL = register("copper_rail", CopperRailBlock::new);
		GOLDEN_RAIL = register("golden_rail", GoldenRailBlock::new);
		GOLDEN_BULB = register("golden_bulb", GoldenBulbBlock::new);
		IRON_BULB = register("iron_bulb", IronBulbBlock::new);
		IRON_BULB_LIT = register("iron_bulb_lit", IronBulbLitBlock::new);
		GOLDEN_BULB_LIT = register("golden_bulb_lit", GoldenBulbLitBlock::new);
		AMETHYST_ORE = register("amethyst_ore", AmethystOreBlock::new);
		RESIN_ORE = register("resin_ore", ResinOreBlock::new);
		QUARTZ_ORE = register("quartz_ore", QuartzOreBlock::new);
		DEEPSLATE_QUARTZ_ORE = register("deepslate_quartz_ore", DeepslateQuartzOreBlock::new);
		DEEPSLATE_AMETHYST_ORE = register("deepslate_amethyst_ore", DeepslateAmethystOreBlock::new);
		DEEPSLATE_RESIN_ORE = register("deepslate_resin_ore", DeepslateResinOreBlock::new);
		ANDESITE_AMETHYST_ORE = register("andesite_amethyst_ore", AndesiteAmethystOreBlock::new);
		DIORITE_AMETHYST_ORE = register("diorite_amethyst_ore", DioriteAmethystOreBlock::new);
		GRANITE_AMETHYST_ORE = register("granite_amethyst_ore", GraniteAmethystOreBlock::new);
		TUFF_AMETHYST_ORE = register("tuff_amethyst_ore", TuffAmethystOreBlock::new);
		ANDESITE_RESIN_ORE = register("andesite_resin_ore", AndesiteResinOreBlock::new);
		DIORITE_RESIN_ORE = register("diorite_resin_ore", DioriteResinOreBlock::new);
		GRANITE_RESIN_ORE = register("granite_resin_ore", GraniteResinOreBlock::new);
		TUFF_RESIN_ORE = register("tuff_resin_ore", TuffResinOreBlock::new);
		ANDESITE_QUARTZ_ORE = register("andesite_quartz_ore", AndesiteQuartzOreBlock::new);
		DIORITE_QUARTZ_ORE = register("diorite_quartz_ore", DioriteQuartzOreBlock::new);
		GRANITE_QUARTZ_ORE = register("granite_quartz_ore", GraniteQuartzOreBlock::new);
		TUFF_QUARTZ_ORE = register("tuff_quartz_ore", TuffQuartzOreBlock::new);
		CLAY_AMETHYST_ORE = register("clay_amethyst_ore", ClayAmethystOreBlock::new);
		CALCITE_AMETHYST_ORE = register("calcite_amethyst_ore", CalciteAmethystOreBlock::new);
		BASALT_AMETHYST_ORE = register("basalt_amethyst_ore", BasaltAmethystOreBlock::new);
		PALE_MOSS_RESIN_ORE = register("pale_moss_resin_ore", PaleMossResinOreBlock::new);
		BASALT_QUARTZ_ORE = register("basalt_quartz_ore", BasaltQuartzOreBlock::new);
		ANDESITE_DIAMOND_ORE = register("andesite_diamond_ore", AndesiteDiamondOreBlock::new);
		ANDESITE_COAL_ORE = register("andesite_coal_ore", AndesiteCoalOreBlock::new);
		ANDESITE_REDSTONE_ORE = register("andesite_redstone_ore", AndesiteRedstoneOreBlock::new);
		ANDESITE_EMERALD_ORE = register("andesite_emerald_ore", AndesiteEmeraldOreBlock::new);
		ANDESITE_GOLD_ORE = register("andesite_gold_ore", AndesiteGoldOreBlock::new);
		ANDESITE_IRON_ORE = register("andesite_iron_ore", AndesiteIronOreBlock::new);
		ANDESITE_LAPIS_LAZULI_ORE = register("andesite_lapis_lazuli_ore", AndesiteLapisLazuliOreBlock::new);
		ANDESITE_COPPER_ORE = register("andesite_copper_ore", AndesiteCopperOreBlock::new);
		DIORITE_DIAMOND_ORE = register("diorite_diamond_ore", DioriteDiamondOreBlock::new);
		GRANITE_DIAMOND_ORE = register("granite_diamond_ore", GraniteDiamondOreBlock::new);
		OBSIDIAN_DIAMOND_ORE = register("obsidian_diamond_ore", ObsidianDiamondOreBlock::new);
		TUFF_DIAMOND_ORE = register("tuff_diamond_ore", TuffDiamondOreBlock::new);
		SANDSTONE_DIAMOND_ORE = register("sandstone_diamond_ore", SandstoneDiamondOreBlock::new);
		DIORITE_EMERALD_ORE = register("diorite_emerald_ore", DioriteEmeraldOreBlock::new);
		GRANITE_EMERALD_ORE = register("granite_emerald_ore", GraniteEmeraldOreBlock::new);
		TUFF_EMERALD_ORE = register("tuff_emerald_ore", TuffEmeraldOreBlock::new);
		SANDSTONE_EMERALD_ORE = register("sandstone_emerald_ore", SandstoneEmeraldOreBlock::new);
		GRANITE_COAL_ORE = register("granite_coal_ore", GraniteCoalOreBlock::new);
		DIORITE_COAL_ORE = register("diorite_coal_ore", DioriteCoalOreBlock::new);
		TUFF_COAL_ORE = register("tuff_coal_ore", TuffCoalOreBlock::new);
		SANDSTONE_COAL_ORE = register("sandstone_coal_ore", SandstoneCoalOreBlock::new);
		DIORITE_GOLD_ORE = register("diorite_gold_ore", DioriteGoldOreBlock::new);
		GRANITE_GOLD_ORE = register("granite_gold_ore", GraniteGoldOreBlock::new);
		TUFF_GOLD_ORE = register("tuff_gold_ore", TuffGoldOreBlock::new);
		SANDSTONE_GOLD_ORE = register("sandstone_gold_ore", SandstoneGoldOreBlock::new);
		TERRACOTTA_GOLD_ORE = register("terracotta_gold_ore", TerracottaGoldOreBlock::new);
		BASALT_GOLD_ORE = register("basalt_gold_ore", BasaltGoldOreBlock::new);
		RED_SANDSTONE_GOLD_ORE = register("red_sandstone_gold_ore", RedSandstoneGoldOreBlock::new);
		TUFF_IRON_ORE = register("tuff_iron_ore", TuffIronOreBlock::new);
		SANDSTONE_IRON_ORE = register("sandstone_iron_ore", SandstoneIronOreBlock::new);
		GRANITE_IRON_ORE = register("granite_iron_ore", GraniteIronOreBlock::new);
		DIORITE_IRON_ORE = register("diorite_iron_ore", DioriteIronOreBlock::new);
		DIORITE_COPPER_ORE = register("diorite_copper_ore", DioriteCopperOreBlock::new);
		GRANITE_COPPER_ORE = register("granite_copper_ore", GraniteCopperOreBlock::new);
		TUFF_COPPER_ORE = register("tuff_copper_ore", TuffCopperOreBlock::new);
		DRIPSTONE_COPPER_ORE = register("dripstone_copper_ore", DripstoneCopperOreBlock::new);
		DIORITE_REDSTONE_ORE = register("diorite_redstone_ore", DioriteRedstoneOreBlock::new);
		GRANITE_REDSTONE_ORE = register("granite_redstone_ore", GraniteRedstoneOreBlock::new);
		SANDSTONE_REDSTONE_ORE = register("sandstone_redstone_ore", SandstoneRedstoneOreBlock::new);
		TUFF_REDSTONE_ORE = register("tuff_redstone_ore", TuffRedstoneOreBlock::new);
		DIORITE_LAPIS_LAZULI_ORE = register("diorite_lapis_lazuli_ore", DioriteLapisLazuliOreBlock::new);
		GRANITE_LAPIS_LAZULI_ORE = register("granite_lapis_lazuli_ore", GraniteLapisLazuliOreBlock::new);
		SANDSTONE_LAPIS_LAZULI_ORE = register("sandstone_lapis_lazuli_ore", SandstoneLapisLazuliOreBlock::new);
		TUFF_LAPIS_LAZULI_ORE = register("tuff_lapis_lazuli_ore", TuffLapisLazuliOreBlock::new);
		COPPER_DANDELION = register("copper_dandelion", CopperDandelionBlock::new);
		NETHERITE_DANDELION = register("netherite_dandelion", NetheriteDandelionBlock::new);
		IRON_DANDELION = register("iron_dandelion", IronDandelionBlock::new);
		DIAMOND_DANDELION = register("diamond_dandelion", DiamondDandelionBlock::new);
		EMERALD_WALL = register("emerald_wall", EmeraldWallBlock::new);
		EMERALD_SLAB = register("emerald_slab", EmeraldSlabBlock::new);
		EMERALD_STAIRS = register("emerald_stairs", EmeraldStairsBlock::new);
		COAL_WALL = register("coal_wall", CoalWallBlock::new);
		COAL_STAIRS = register("coal_stairs", CoalStairsBlock::new);
		COAL_SLAB = register("coal_slab", CoalSlabBlock::new);
		DIRT_COAL_ORE = register("dirt_coal_ore", DirtCoalOreBlock::new);
		DIRT_GOLD_ORE = register("dirt_gold_ore", DirtGoldOreBlock::new);
		DIRT_RESIN_ORE = register("dirt_resin_ore", DirtResinOreBlock::new);
		BURNT_OUT_TORCH = register("burnt_out_torch", BurntOutTorchBlock::new);
		BLOCK_OF_BURNING_COAL = register("block_of_burning_coal", BlockOfBurningCoalBlock::new);
		BLOCK_OF_CHARCOAL = register("block_of_charcoal", BlockOfCharcoalBlock::new);
		POWDERED_GOLD = register("powdered_gold", PowderedGoldBlock::new);
		CLUMPED_GOLD = register("clumped_gold", ClumpedGoldBlock::new);
		METALLIC_GOLD = register("metallic_gold", MetallicGoldBlock::new);
		BEVELED_GOLD = register("beveled_gold", BeveledGoldBlock::new);
		ROUGH_GOLD = register("rough_gold", RoughGoldBlock::new);
		SPECKLED_GOLD = register("speckled_gold", SpeckledGoldBlock::new);
		CLEAR_GOLD = register("clear_gold", ClearGoldBlock::new);
		STONY_GOLD = register("stony_gold", StonyGoldBlock::new);
		CRYSTALIZED_GOLD = register("crystalized_gold", CrystalizedGoldBlock::new);
		BOLTED_EMERALD = register("bolted_emerald", BoltedEmeraldBlock::new);
		POWDERED_EMERALD = register("powdered_emerald", PowderedEmeraldBlock::new);
		CLUMPED_EMERALD = register("clumped_emerald", ClumpedEmeraldBlock::new);
		METALLIC_EMERALD = register("metallic_emerald", MetallicEmeraldBlock::new);
		GLOSSY_EMERALD = register("glossy_emerald", GlossyEmeraldBlock::new);
		ROUGH_EMERALD = register("rough_emerald", RoughEmeraldBlock::new);
		SPECKLED_EMERALD = register("speckled_emerald", SpeckledEmeraldBlock::new);
		CLEAR_EMERALD = register("clear_emerald", ClearEmeraldBlock::new);
		STONY_EMERALD = register("stony_emerald", StonyEmeraldBlock::new);
		CRYSTALIZED_EMERALD = register("crystalized_emerald", CrystalizedEmeraldBlock::new);
		BEVELED_AMETHYST = register("beveled_amethyst", BeveledAmethystBlock::new);
		BOLTED_AMETHYST = register("bolted_amethyst", BoltedAmethystBlock::new);
		POWDERED_AMETHYST = register("powdered_amethyst", PowderedAmethystBlock::new);
		CLUMPED_AMETHYST = register("clumped_amethyst", ClumpedAmethystBlock::new);
		METALLIC_AMETHYST = register("metallic_amethyst", MetallicAmethystBlock::new);
		GLOSSY_AMETHYST = register("glossy_amethyst", GlossyAmethystBlock::new);
		ROUGH_AMETHYST = register("rough_amethyst", RoughAmethystBlock::new);
		SPECKLED_AMETHYST = register("speckled_amethyst", SpeckledAmethystBlock::new);
		CLEAR_AMETHYST = register("clear_amethyst", ClearAmethystBlock::new);
		STONY_AMETHYST = register("stony_amethyst", StonyAmethystBlock::new);
		BEVELED_QUARTZ = register("beveled_quartz", BeveledQuartzBlock::new);
		BOLTED_QUARTZ = register("bolted_quartz", BoltedQuartzBlock::new);
		POWDERED_QUARTZ = register("powdered_quartz", PowderedQuartzBlock::new);
		CLUMPED_QUARTZ = register("clumped_quartz", ClumpedQuartzBlock::new);
		METALLIC_QUARTZ = register("metallic_quartz", MetallicQuartzBlock::new);
		GLOSSY_QUARTZ = register("glossy_quartz", GlossyQuartzBlock::new);
		ROUGH_QUARTZ = register("rough_quartz", RoughQuartzBlock::new);
		SPECKLED_QUARTZ = register("speckled_quartz", SpeckledQuartzBlock::new);
		STONY_QUARTZ = register("stony_quartz", StonyQuartzBlock::new);
		CRYSTALIZED_QUARTZ = register("crystalized_quartz", CrystalizedQuartzBlock::new);
		BEVELED_RESIN = register("beveled_resin", BeveledResinBlock::new);
		BOLTED_RESIN = register("bolted_resin", BoltedResinBlock::new);
		POWDERED_RESIN = register("powdered_resin", PowderedResinBlock::new);
		METALLIC_RESIN = register("metallic_resin", MetallicResinBlock::new);
		GLOSSY_RESIN = register("glossy_resin", GlossyResinBlock::new);
		ROUGH_RESIN = register("rough_resin", RoughResinBlock::new);
		SPECKLED_RESIN = register("speckled_resin", SpeckledResinBlock::new);
		CLEAR_RESIN = register("clear_resin", ClearResinBlock::new);
		STONY_RESIN = register("stony_resin", StonyResinBlock::new);
		CRYSTALIZED_RESIN = register("crystalized_resin", CrystalizedResinBlock::new);
		TOUGH_COAL = register("tough_coal", ToughCoalBlock::new);
		BEVELED_COAL = register("beveled_coal", BeveledCoalBlock::new);
		BOLTED_COAL = register("bolted_coal", BoltedCoalBlock::new);
		POWDERED_COAL = register("powdered_coal", PowderedCoalBlock::new);
		METALLIC_COAL = register("metallic_coal", MetallicCoalBlock::new);
		GLOSSY_COAL = register("glossy_coal", GlossyCoalBlock::new);
		SPECKLED_COAL = register("speckled_coal", SpeckledCoalBlock::new);
		CLUMPED_COAL = register("clumped_coal", ClumpedCoalBlock::new);
		CLEAR_COAL = register("clear_coal", ClearCoalBlock::new);
		CRYSTALIZED_COAL = register("crystalized_coal", CrystalizedCoalBlock::new);
		TOUGH_LAPIS_LAZULI = register("tough_lapis_lazuli", ToughLapisLazuliBlock::new);
		BEVELED_LAPIS_LAZULI = register("beveled_lapis_lazuli", BeveledLapisLazuliBlock::new);
		BOLTED_LAPIS_LAZULI = register("bolted_lapis_lazuli", BoltedLapisLazuliBlock::new);
		POWDERED_LAPIS_LAZULI = register("powdered_lapis_lazuli", PowderedLapisLazuliBlock::new);
		METALLIC_LAPIS_LAZULI = register("metallic_lapis_lazuli", MetallicLapisLazuliBlock::new);
		GLOSSY_LAPIS_LAZULI = register("glossy_lapis_lazuli", GlossyLapisLazuliBlock::new);
		STONY_LAPIS_LAZULI = register("stony_lapis_lazuli", StonyLapisLazuliBlock::new);
		CLUMPED_LAPIS_LAZULI = register("clumped_lapis_lazuli", ClumpedLapisLazuliBlock::new);
		CLEAR_LAPIS_LAZULI = register("clear_lapis_lazuli", ClearLapisLazuliBlock::new);
		CRYSTALIZED_LAPIS_LAZULI = register("crystalized_lapis_lazuli", CrystalizedLapisLazuliBlock::new);
		TOUGH_REDSTONE = register("tough_redstone", ToughRedstoneBlock::new);
		BEVELED_REDSTONE = register("beveled_redstone", BeveledRedstoneBlock::new);
		BOLTED_REDSTONE = register("bolted_redstone", BoltedRedstoneBlock::new);
		SPECKLED_REDSTONE = register("speckled_redstone", SpeckledRedstoneBlock::new);
		METALLIC_REDSTONE = register("metallic_redstone", MetallicRedstoneBlock::new);
		GLOSSY_REDSTONE = register("glossy_redstone", GlossyRedstoneBlock::new);
		STONY_REDSTONE = register("stony_redstone", StonyRedstoneBlock::new);
		CLUMPED_REDSTONE = register("clumped_redstone", ClumpedRedstoneBlock::new);
		CLEAR_REDSTONE = register("clear_redstone", ClearRedstoneBlock::new);
		CRYSTALIZED_REDSTONE = register("crystalized_redstone", CrystalizedRedstoneBlock::new);
		TOUGH_COPPER = register("tough_copper", ToughCopperBlock::new);
		BEVELED_COPPER = register("beveled_copper", BeveledCopperBlock::new);
		POWDERED_COPPER = register("powdered_copper", PowderedCopperBlock::new);
		SPECKLED_COPPER = register("speckled_copper", SpeckledCopperBlock::new);
		METALLIC_COPPER = register("metallic_copper", MetallicCopperBlock::new);
		GLOSSY_COPPER = register("glossy_copper", GlossyCopperBlock::new);
		STONY_COPPER = register("stony_copper", StonyCopperBlock::new);
		CLUMPED_COPPER = register("clumped_copper", ClumpedCopperBlock::new);
		CLEAR_COPPER = register("clear_copper", ClearCopperBlock::new);
		CRYSTALIZED_COPPER = register("crystalized_copper", CrystalizedCopperBlock::new);
		TOUGH_IRON = register("tough_iron", ToughIronBlock::new);
		BEVELED_IRON = register("beveled_iron", BeveledIronBlock::new);
		POWDERED_IRON = register("powdered_iron", PowderedIronBlock::new);
		SPECKLED_IRON = register("speckled_iron", SpeckledIronBlock::new);
		GLOSSY_IRON = register("glossy_iron", GlossyIronBlock::new);
		STONY_IRON = register("stony_iron", StonyIronBlock::new);
		CLUMPED_IRON = register("clumped_iron", ClumpedIronBlock::new);
		CLEAR_IRON = register("clear_iron", ClearIronBlock::new);
		CRYSTALIZED_IRON = register("crystalized_iron", CrystalizedIronBlock::new);
		METALLIC_NETHERITE = register("metallic_netherite", MetallicNetheriteBlock::new);
		BEVELED_NETHERITE = register("beveled_netherite", BeveledNetheriteBlock::new);
		POWDERED_NETHERITE = register("powdered_netherite", PowderedNetheriteBlock::new);
		SPECKLED_NETHERITE = register("speckled_netherite", SpeckledNetheriteBlock::new);
		GLOSSY_NETHERITE = register("glossy_netherite", GlossyNetheriteBlock::new);
		STONY_NETHERITE = register("stony_netherite", StonyNetheriteBlock::new);
		CLUMPED_NETHERITE = register("clumped_netherite", ClumpedNetheriteBlock::new);
		CLEAR_NETHERITE = register("clear_netherite", ClearNetheriteBlock::new);
		CRYSTALIZED_NETHERITE = register("crystalized_netherite", CrystalizedNetheriteBlock::new);
		TOUGH_DIAMOND = register("tough_diamond", ToughDiamondBlock::new);
		METALLIC_DIAMOND = register("metallic_diamond", MetallicDiamondBlock::new);
		BEVELED_DIAMOND = register("beveled_diamond", BeveledDiamondBlock::new);
		POWDERED_DIAMOND = register("powdered_diamond", PowderedDiamondBlock::new);
		SPECKLED_DIAMOND = register("speckled_diamond", SpeckledDiamondBlock::new);
		BOLTED_DIAMOND = register("bolted_diamond", BoltedDiamondBlock::new);
		STONY_DIAMOND = register("stony_diamond", StonyDiamondBlock::new);
		CLUMPED_DIAMOND = register("clumped_diamond", ClumpedDiamondBlock::new);
		CLEAR_DIAMOND = register("clear_diamond", ClearDiamondBlock::new);
		CRYSTALIZED_DIAMOND = register("crystalized_diamond", CrystalizedDiamondBlock::new);
		BASALT_NETHERITE_ORE = register("basalt_netherite_ore", BasaltNetheriteOreBlock::new);
		BONE_BLOCK_NETHERITE_ORE = register("bone_block_netherite_ore", BoneBlockNetheriteOreBlock::new);
		COPPER_CAMPFIRE = register("copper_campfire", CopperCampfireBlock::new);
		PRISMARINE_ORE = register("prismarine_ore", PrismarineOreBlock::new);
		DEEPSLATE_PRISMARINE_ORE = register("deepslate_prismarine_ore", DeepslatePrismarineOreBlock::new);
		BEVELED_PRISMARINE = register("beveled_prismarine", BeveledPrismarineBlock::new);
		CLUMPED_PRISMARINE = register("clumped_prismarine", ClumpedPrismarineBlock::new);
		CLEAR_PRISMARINE = register("clear_prismarine", ClearPrismarineBlock::new);
		CRYSTALIZED_PRISMARINE = register("crystalized_prismarine", CrystalizedPrismarineBlock::new);
		BOLTED_PRISMARINE = register("bolted_prismarine", BoltedPrismarineBlock::new);
		STONY_PRISMARINE = register("stony_prismarine", StonyPrismarineBlock::new);
		ROUGH_PRISMARINE = register("rough_prismarine", RoughPrismarineBlock::new);
		METALLIC_PRISMARINE = register("metallic_prismarine", MetallicPrismarineBlock::new);
		GLOSSY_PRISMARINE = register("glossy_prismarine", GlossyPrismarineBlock::new);
		POWDERED_PRISMARINE = register("powdered_prismarine", PowderedPrismarineBlock::new);
		SPECKLED_PRISMARINE = register("speckled_prismarine", SpeckledPrismarineBlock::new);
		HUE_AMETHYST = register("hue_amethyst", HueAmethystBlock::new);
		HUE_COAL = register("hue_coal", HueCoalBlock::new);
		HUE_COPPER = register("hue_copper", HueCopperBlock::new);
		HUE_DIAMOND = register("hue_diamond", HueDiamondBlock::new);
		HUE_EMERALD = register("hue_emerald", HueEmeraldBlock::new);
		HUE_GOLD = register("hue_gold", HueGoldBlock::new);
		HUE_IRON = register("hue_iron", HueIronBlock::new);
		HUE_LAPIS_LAZULI = register("hue_lapis_lazuli", HueLapisLazuliBlock::new);
		HUE_NETHERITE = register("hue_netherite", HueNetheriteBlock::new);
		HUE_QUARTZ = register("hue_quartz", HueQuartzBlock::new);
		HUE_REDSTONE = register("hue_redstone", HueRedstoneBlock::new);
		HUE_RESIN = register("hue_resin", HueResinBlock::new);
		MYSTERY_ORE = register("mystery_ore", MysteryOreBlock::new);
		DEEPSLATE_MYSTERY_ORE = register("deepslate_mystery_ore", DeepslateMysteryOreBlock::new);
	}

	// Start of user code block custom blocks
	// End of user code block custom blocks
	private static <B extends Block> DeferredBlock<B> register(String name, Function<BlockBehaviour.Properties, ? extends B> supplier) {
		return REGISTRY.registerBlock(name, supplier);
	}
}