package com.zing.zingsorestiers.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.SpawnEggItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import com.zing.zingsorestiers.item.*;
import com.zing.zingsorestiers.ZingsOresAndTiersMod;

import java.util.function.Function;

public class ZingsOresAndTiersModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(ZingsOresAndTiersMod.MODID);
	public static final DeferredItem<Item> REDSTONE_ARMOR_HELMET;
	public static final DeferredItem<Item> REDSTONE_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> REDSTONE_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> REDSTONE_ARMOR_BOOTS;
	public static final DeferredItem<Item> LAPIS_LAZULI_ARMOR_HELMET;
	public static final DeferredItem<Item> LAPIS_LAZULI_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> LAPIS_LAZULI_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> LAPIS_LAZULI_ARMOR_BOOTS;
	public static final DeferredItem<Item> EMERALD_ARMOR_HELMET;
	public static final DeferredItem<Item> EMERALD_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> EMERALD_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> EMERALD_ARMOR_BOOTS;
	public static final DeferredItem<Item> AMETHYST_ARMOR_HELMET;
	public static final DeferredItem<Item> AMETHYST_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> AMETHYST_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> AMETHYST_ARMOR_BOOTS;
	public static final DeferredItem<Item> QUARTZ_ARMOR_HELMET;
	public static final DeferredItem<Item> QUARTZ_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> QUARTZ_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> QUARTZ_ARMOR_BOOTS;
	public static final DeferredItem<Item> RESIN_ARMOR_HELMET;
	public static final DeferredItem<Item> RESIN_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> RESIN_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> RESIN_ARMOR_BOOTS;
	public static final DeferredItem<Item> REDSTONE_SWORD;
	public static final DeferredItem<Item> REDSTONE_AXE;
	public static final DeferredItem<Item> REDSTONE_HOE;
	public static final DeferredItem<Item> REDSTONE_PICKAXE;
	public static final DeferredItem<Item> REDSTONE_SHOVEL;
	public static final DeferredItem<Item> RESIN_BULB_LIT;
	public static final DeferredItem<Item> RESIN_BULB;
	public static final DeferredItem<Item> RESIN_LANTERN;
	public static final DeferredItem<Item> RESIN_TORCH;
	public static final DeferredItem<Item> GOLDEN_LANTERN;
	public static final DeferredItem<Item> GOLDEN_TORCH;
	public static final DeferredItem<Item> NETHERITE_NUGGET;
	public static final DeferredItem<Item> IRON_LANTERN;
	public static final DeferredItem<Item> IRON_TORCH;
	public static final DeferredItem<Item> NETHERITE_LANTERN;
	public static final DeferredItem<Item> NETHERITE_TORCH;
	public static final DeferredItem<Item> WARPED_NETHERITE_LANTERN;
	public static final DeferredItem<Item> WARPED_NETHERITE_TORCH;
	public static final DeferredItem<Item> CRIMSON_NETHERITE_LANTERN;
	public static final DeferredItem<Item> CRIMSON_NETHERITE_TORCH;
	public static final DeferredItem<Item> NETHERITE_LIGHTNING_ROD;
	public static final DeferredItem<Item> GOLDEN_LIGHTNING_ROD;
	public static final DeferredItem<Item> IRON_LIGHTNING_ROD;
	public static final DeferredItem<Item> NETHERITE_CHAIN;
	public static final DeferredItem<Item> GOLDEN_CHAIN;
	public static final DeferredItem<Item> NETHERITE_BULB;
	public static final DeferredItem<Item> CRIMSON_NETHERITE_BULB;
	public static final DeferredItem<Item> WARPED_NETHERITE_BULB;
	public static final DeferredItem<Item> NETHERITE_BULB_LIT;
	public static final DeferredItem<Item> CRIMSON_NETHERITE_BULB_LIT;
	public static final DeferredItem<Item> WARPED_NETHERITE_BULB_LIT;
	public static final DeferredItem<Item> BOLTED_NETHERITE;
	public static final DeferredItem<Item> NETHERITE_RAIL;
	public static final DeferredItem<Item> NETHERITE_TRAPDOOR;
	public static final DeferredItem<Item> NETHERITE_GRATE;
	public static final DeferredItem<Item> CUT_NETHERITE;
	public static final DeferredItem<Item> CUT_NETHERITE_STAIRS;
	public static final DeferredItem<Item> CUT_NETHERITE_SLAB;
	public static final DeferredItem<Item> NETHERITE_BARS;
	public static final DeferredItem<Item> NETHERITE_DOOR;
	public static final DeferredItem<Item> CUT_IRON;
	public static final DeferredItem<Item> BOLTED_IRON;
	public static final DeferredItem<Item> CUT_GOLD;
	public static final DeferredItem<Item> BOLTED_GOLD;
	public static final DeferredItem<Item> IRON_BRUSH;
	public static final DeferredItem<Item> NETHERITE_BRUSH;
	public static final DeferredItem<Item> GOLDEN_BRUSH;
	public static final DeferredItem<Item> GOLDEN_SHEARS;
	public static final DeferredItem<Item> COPPER_SHEARS;
	public static final DeferredItem<Item> NETHERITE_SHEARS;
	public static final DeferredItem<Item> GOLDEN_BUCKET;
	public static final DeferredItem<Item> COPPER_BUCKET;
	public static final DeferredItem<Item> NETHERITE_BUCKET;
	public static final DeferredItem<Item> GOLDEN_WATER_BUCKET;
	public static final DeferredItem<Item> COPPER_WATER_BUCKET;
	public static final DeferredItem<Item> NETHERITE_WATER_BUCKET;
	public static final DeferredItem<Item> GOLDEN_LAVA_BUCKET;
	public static final DeferredItem<Item> NETHERITE_LAVA_BUCKET;
	public static final DeferredItem<Item> COPPER_LAVA_BUCKET;
	public static final DeferredItem<Item> COPPER_SCRAP;
	public static final DeferredItem<Item> GOLDEN_SCRAP;
	public static final DeferredItem<Item> IRON_SCRAP;
	public static final DeferredItem<Item> FLINT_AND_NETHERITE;
	public static final DeferredItem<Item> FLINT_AND_GOLD;
	public static final DeferredItem<Item> FLINT_AND_COPPER;
	public static final DeferredItem<Item> GOLDEN_BARS;
	public static final DeferredItem<Item> GOLDEN_TRAPDOOR;
	public static final DeferredItem<Item> GOLDEN_DOOR;
	public static final DeferredItem<Item> GOLDEN_GRATE;
	public static final DeferredItem<Item> IRON_GRATE;
	public static final DeferredItem<Item> COPPER_RAIL;
	public static final DeferredItem<Item> GOLDEN_RAIL;
	public static final DeferredItem<Item> GOLDEN_BULB;
	public static final DeferredItem<Item> IRON_BULB;
	public static final DeferredItem<Item> IRON_BULB_LIT;
	public static final DeferredItem<Item> GOLDEN_BULB_LIT;
	public static final DeferredItem<Item> LAPIS_LAZULI_SWORD;
	public static final DeferredItem<Item> EMERALD_SWORD;
	public static final DeferredItem<Item> QUARTZ_SWORD;
	public static final DeferredItem<Item> AMETHYST_SWORD;
	public static final DeferredItem<Item> RESIN_SWORD;
	public static final DeferredItem<Item> LAPIS_LAZULI_AXE;
	public static final DeferredItem<Item> EMERALD_AXE;
	public static final DeferredItem<Item> QUARTZ_AXE;
	public static final DeferredItem<Item> AMETHYST_AXE;
	public static final DeferredItem<Item> RESIN_AXE;
	public static final DeferredItem<Item> LAPIS_LAZULI_HOE;
	public static final DeferredItem<Item> EMERALD_HOE;
	public static final DeferredItem<Item> QUARTZ_HOE;
	public static final DeferredItem<Item> AMETHYST_HOE;
	public static final DeferredItem<Item> RESIN_HOE;
	public static final DeferredItem<Item> LAPIS_LAZULI_PICKAXE;
	public static final DeferredItem<Item> EMERALD_PICKAXE;
	public static final DeferredItem<Item> QUARTZ_PICKAXE;
	public static final DeferredItem<Item> AMETHYST_PICKAXE;
	public static final DeferredItem<Item> RESIN_PICKAXE;
	public static final DeferredItem<Item> LAPIS_LAZULI_SHOVEL;
	public static final DeferredItem<Item> EMERALD_SHOVEL;
	public static final DeferredItem<Item> QUARTZ_SHOVEL;
	public static final DeferredItem<Item> AMETHYST_SHOVEL;
	public static final DeferredItem<Item> RESIN_SHOVEL;
	public static final DeferredItem<Item> REDSTONE_UPGRADE;
	public static final DeferredItem<Item> LAPIS_LAZULI_UPGRADE;
	public static final DeferredItem<Item> AMETHYST_ORE;
	public static final DeferredItem<Item> RESIN_ORE;
	public static final DeferredItem<Item> QUARTZ_ORE;
	public static final DeferredItem<Item> DEEPSLATE_QUARTZ_ORE;
	public static final DeferredItem<Item> DEEPSLATE_AMETHYST_ORE;
	public static final DeferredItem<Item> DEEPSLATE_RESIN_ORE;
	public static final DeferredItem<Item> ANDESITE_AMETHYST_ORE;
	public static final DeferredItem<Item> DIORITE_AMETHYST_ORE;
	public static final DeferredItem<Item> GRANITE_AMETHYST_ORE;
	public static final DeferredItem<Item> TUFF_AMETHYST_ORE;
	public static final DeferredItem<Item> ANDESITE_RESIN_ORE;
	public static final DeferredItem<Item> DIORITE_RESIN_ORE;
	public static final DeferredItem<Item> GRANITE_RESIN_ORE;
	public static final DeferredItem<Item> TUFF_RESIN_ORE;
	public static final DeferredItem<Item> ANDESITE_QUARTZ_ORE;
	public static final DeferredItem<Item> DIORITE_QUARTZ_ORE;
	public static final DeferredItem<Item> GRANITE_QUARTZ_ORE;
	public static final DeferredItem<Item> TUFF_QUARTZ_ORE;
	public static final DeferredItem<Item> CLAY_AMETHYST_ORE;
	public static final DeferredItem<Item> CALCITE_AMETHYST_ORE;
	public static final DeferredItem<Item> BASALT_AMETHYST_ORE;
	public static final DeferredItem<Item> PALE_MOSS_RESIN_ORE;
	public static final DeferredItem<Item> BASALT_QUARTZ_ORE;
	public static final DeferredItem<Item> ANDESITE_DIAMOND_ORE;
	public static final DeferredItem<Item> ANDESITE_COAL_ORE;
	public static final DeferredItem<Item> ANDESITE_REDSTONE_ORE;
	public static final DeferredItem<Item> ANDESITE_EMERALD_ORE;
	public static final DeferredItem<Item> ANDESITE_GOLD_ORE;
	public static final DeferredItem<Item> ANDESITE_IRON_ORE;
	public static final DeferredItem<Item> ANDESITE_LAPIS_LAZULI_ORE;
	public static final DeferredItem<Item> ANDESITE_COPPER_ORE;
	public static final DeferredItem<Item> DIORITE_DIAMOND_ORE;
	public static final DeferredItem<Item> GRANITE_DIAMOND_ORE;
	public static final DeferredItem<Item> OBSIDIAN_DIAMOND_ORE;
	public static final DeferredItem<Item> TUFF_DIAMOND_ORE;
	public static final DeferredItem<Item> SANDSTONE_DIAMOND_ORE;
	public static final DeferredItem<Item> DIORITE_EMERALD_ORE;
	public static final DeferredItem<Item> GRANITE_EMERALD_ORE;
	public static final DeferredItem<Item> TUFF_EMERALD_ORE;
	public static final DeferredItem<Item> SANDSTONE_EMERALD_ORE;
	public static final DeferredItem<Item> GRANITE_COAL_ORE;
	public static final DeferredItem<Item> DIORITE_COAL_ORE;
	public static final DeferredItem<Item> TUFF_COAL_ORE;
	public static final DeferredItem<Item> SANDSTONE_COAL_ORE;
	public static final DeferredItem<Item> DIORITE_GOLD_ORE;
	public static final DeferredItem<Item> GRANITE_GOLD_ORE;
	public static final DeferredItem<Item> TUFF_GOLD_ORE;
	public static final DeferredItem<Item> SANDSTONE_GOLD_ORE;
	public static final DeferredItem<Item> TERRACOTTA_GOLD_ORE;
	public static final DeferredItem<Item> BASALT_GOLD_ORE;
	public static final DeferredItem<Item> RED_SANDSTONE_GOLD_ORE;
	public static final DeferredItem<Item> TUFF_IRON_ORE;
	public static final DeferredItem<Item> SANDSTONE_IRON_ORE;
	public static final DeferredItem<Item> GRANITE_IRON_ORE;
	public static final DeferredItem<Item> DIORITE_IRON_ORE;
	public static final DeferredItem<Item> DIORITE_COPPER_ORE;
	public static final DeferredItem<Item> GRANITE_COPPER_ORE;
	public static final DeferredItem<Item> TUFF_COPPER_ORE;
	public static final DeferredItem<Item> DRIPSTONE_COPPER_ORE;
	public static final DeferredItem<Item> DIORITE_REDSTONE_ORE;
	public static final DeferredItem<Item> GRANITE_REDSTONE_ORE;
	public static final DeferredItem<Item> SANDSTONE_REDSTONE_ORE;
	public static final DeferredItem<Item> TUFF_REDSTONE_ORE;
	public static final DeferredItem<Item> DIORITE_LAPIS_LAZULI_ORE;
	public static final DeferredItem<Item> GRANITE_LAPIS_LAZULI_ORE;
	public static final DeferredItem<Item> SANDSTONE_LAPIS_LAZULI_ORE;
	public static final DeferredItem<Item> TUFF_LAPIS_LAZULI_ORE;
	public static final DeferredItem<Item> GOLDEN_GOLEM_SPAWN_EGG;
	public static final DeferredItem<Item> NETHERITE_GOLEM_SPAWN_EGG;
	public static final DeferredItem<Item> ZING_BOOK_VOLUME_SIX;
	public static final DeferredItem<Item> COPPER_DANDELION;
	public static final DeferredItem<Item> NETHERITE_DANDELION;
	public static final DeferredItem<Item> IRON_DANDELION;
	public static final DeferredItem<Item> DIAMOND_DANDELION;
	public static final DeferredItem<Item> EMERALD_WALL;
	public static final DeferredItem<Item> EMERALD_SLAB;
	public static final DeferredItem<Item> EMERALD_STAIRS;
	public static final DeferredItem<Item> COAL_ARMOR_HELMET;
	public static final DeferredItem<Item> COAL_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> COAL_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> COAL_ARMOR_BOOTS;
	public static final DeferredItem<Item> COAL_PICKAXE;
	public static final DeferredItem<Item> COAL_HOE;
	public static final DeferredItem<Item> COAL_SHOVEL;
	public static final DeferredItem<Item> COAL_AXE;
	public static final DeferredItem<Item> COAL_SWORD;
	public static final DeferredItem<Item> COAL_WALL;
	public static final DeferredItem<Item> COAL_STAIRS;
	public static final DeferredItem<Item> COAL_SLAB;
	public static final DeferredItem<Item> DIRT_COAL_ORE;
	public static final DeferredItem<Item> DIRT_GOLD_ORE;
	public static final DeferredItem<Item> DIRT_RESIN_ORE;
	public static final DeferredItem<Item> BURNT_OUT_TORCH;
	public static final DeferredItem<Item> BLOCK_OF_BURNING_COAL;
	public static final DeferredItem<Item> BLOCK_OF_CHARCOAL;
	public static final DeferredItem<Item> BUCKET_OF_COAL;
	public static final DeferredItem<Item> BURNING_COAL;
	public static final DeferredItem<Item> POWDERED_GOLD;
	public static final DeferredItem<Item> CLUMPED_GOLD;
	public static final DeferredItem<Item> METALLIC_GOLD;
	public static final DeferredItem<Item> BEVELED_GOLD;
	public static final DeferredItem<Item> ROUGH_GOLD;
	public static final DeferredItem<Item> SPECKLED_GOLD;
	public static final DeferredItem<Item> CLEAR_GOLD;
	public static final DeferredItem<Item> STONY_GOLD;
	public static final DeferredItem<Item> CRYSTALIZED_GOLD;
	public static final DeferredItem<Item> BOLTED_EMERALD;
	public static final DeferredItem<Item> POWDERED_EMERALD;
	public static final DeferredItem<Item> CLUMPED_EMERALD;
	public static final DeferredItem<Item> METALLIC_EMERALD;
	public static final DeferredItem<Item> GLOSSY_EMERALD;
	public static final DeferredItem<Item> ROUGH_EMERALD;
	public static final DeferredItem<Item> SPECKLED_EMERALD;
	public static final DeferredItem<Item> CLEAR_EMERALD;
	public static final DeferredItem<Item> STONY_EMERALD;
	public static final DeferredItem<Item> CRYSTALIZED_EMERALD;
	public static final DeferredItem<Item> BEVELED_AMETHYST;
	public static final DeferredItem<Item> BOLTED_AMETHYST;
	public static final DeferredItem<Item> POWDERED_AMETHYST;
	public static final DeferredItem<Item> CLUMPED_AMETHYST;
	public static final DeferredItem<Item> METALLIC_AMETHYST;
	public static final DeferredItem<Item> GLOSSY_AMETHYST;
	public static final DeferredItem<Item> ROUGH_AMETHYST;
	public static final DeferredItem<Item> SPECKLED_AMETHYST;
	public static final DeferredItem<Item> CLEAR_AMETHYST;
	public static final DeferredItem<Item> STONY_AMETHYST;
	public static final DeferredItem<Item> BEVELED_QUARTZ;
	public static final DeferredItem<Item> BOLTED_QUARTZ;
	public static final DeferredItem<Item> POWDERED_QUARTZ;
	public static final DeferredItem<Item> CLUMPED_QUARTZ;
	public static final DeferredItem<Item> METALLIC_QUARTZ;
	public static final DeferredItem<Item> GLOSSY_QUARTZ;
	public static final DeferredItem<Item> ROUGH_QUARTZ;
	public static final DeferredItem<Item> SPECKLED_QUARTZ;
	public static final DeferredItem<Item> STONY_QUARTZ;
	public static final DeferredItem<Item> CRYSTALIZED_QUARTZ;
	public static final DeferredItem<Item> BEVELED_RESIN;
	public static final DeferredItem<Item> BOLTED_RESIN;
	public static final DeferredItem<Item> POWDERED_RESIN;
	public static final DeferredItem<Item> METALLIC_RESIN;
	public static final DeferredItem<Item> GLOSSY_RESIN;
	public static final DeferredItem<Item> ROUGH_RESIN;
	public static final DeferredItem<Item> SPECKLED_RESIN;
	public static final DeferredItem<Item> CLEAR_RESIN;
	public static final DeferredItem<Item> STONY_RESIN;
	public static final DeferredItem<Item> CRYSTALIZED_RESIN;
	public static final DeferredItem<Item> TOUGH_COAL;
	public static final DeferredItem<Item> BEVELED_COAL;
	public static final DeferredItem<Item> BOLTED_COAL;
	public static final DeferredItem<Item> POWDERED_COAL;
	public static final DeferredItem<Item> METALLIC_COAL;
	public static final DeferredItem<Item> GLOSSY_COAL;
	public static final DeferredItem<Item> SPECKLED_COAL;
	public static final DeferredItem<Item> CLUMPED_COAL;
	public static final DeferredItem<Item> CLEAR_COAL;
	public static final DeferredItem<Item> CRYSTALIZED_COAL;
	public static final DeferredItem<Item> TOUGH_LAPIS_LAZULI;
	public static final DeferredItem<Item> BEVELED_LAPIS_LAZULI;
	public static final DeferredItem<Item> BOLTED_LAPIS_LAZULI;
	public static final DeferredItem<Item> POWDERED_LAPIS_LAZULI;
	public static final DeferredItem<Item> METALLIC_LAPIS_LAZULI;
	public static final DeferredItem<Item> GLOSSY_LAPIS_LAZULI;
	public static final DeferredItem<Item> STONY_LAPIS_LAZULI;
	public static final DeferredItem<Item> CLUMPED_LAPIS_LAZULI;
	public static final DeferredItem<Item> CLEAR_LAPIS_LAZULI;
	public static final DeferredItem<Item> CRYSTALIZED_LAPIS_LAZULI;
	public static final DeferredItem<Item> TOUGH_REDSTONE;
	public static final DeferredItem<Item> BEVELED_REDSTONE;
	public static final DeferredItem<Item> BOLTED_REDSTONE;
	public static final DeferredItem<Item> SPECKLED_REDSTONE;
	public static final DeferredItem<Item> METALLIC_REDSTONE;
	public static final DeferredItem<Item> GLOSSY_REDSTONE;
	public static final DeferredItem<Item> STONY_REDSTONE;
	public static final DeferredItem<Item> CLUMPED_REDSTONE;
	public static final DeferredItem<Item> CLEAR_REDSTONE;
	public static final DeferredItem<Item> CRYSTALIZED_REDSTONE;
	public static final DeferredItem<Item> TOUGH_COPPER;
	public static final DeferredItem<Item> BEVELED_COPPER;
	public static final DeferredItem<Item> POWDERED_COPPER;
	public static final DeferredItem<Item> SPECKLED_COPPER;
	public static final DeferredItem<Item> METALLIC_COPPER;
	public static final DeferredItem<Item> GLOSSY_COPPER;
	public static final DeferredItem<Item> STONY_COPPER;
	public static final DeferredItem<Item> CLUMPED_COPPER;
	public static final DeferredItem<Item> CLEAR_COPPER;
	public static final DeferredItem<Item> CRYSTALIZED_COPPER;
	public static final DeferredItem<Item> TOUGH_IRON;
	public static final DeferredItem<Item> BEVELED_IRON;
	public static final DeferredItem<Item> POWDERED_IRON;
	public static final DeferredItem<Item> SPECKLED_IRON;
	public static final DeferredItem<Item> GLOSSY_IRON;
	public static final DeferredItem<Item> STONY_IRON;
	public static final DeferredItem<Item> CLUMPED_IRON;
	public static final DeferredItem<Item> CLEAR_IRON;
	public static final DeferredItem<Item> CRYSTALIZED_IRON;
	public static final DeferredItem<Item> METALLIC_NETHERITE;
	public static final DeferredItem<Item> BEVELED_NETHERITE;
	public static final DeferredItem<Item> POWDERED_NETHERITE;
	public static final DeferredItem<Item> SPECKLED_NETHERITE;
	public static final DeferredItem<Item> GLOSSY_NETHERITE;
	public static final DeferredItem<Item> STONY_NETHERITE;
	public static final DeferredItem<Item> CLUMPED_NETHERITE;
	public static final DeferredItem<Item> CLEAR_NETHERITE;
	public static final DeferredItem<Item> CRYSTALIZED_NETHERITE;
	public static final DeferredItem<Item> TOUGH_DIAMOND;
	public static final DeferredItem<Item> METALLIC_DIAMOND;
	public static final DeferredItem<Item> BEVELED_DIAMOND;
	public static final DeferredItem<Item> POWDERED_DIAMOND;
	public static final DeferredItem<Item> SPECKLED_DIAMOND;
	public static final DeferredItem<Item> BOLTED_DIAMOND;
	public static final DeferredItem<Item> STONY_DIAMOND;
	public static final DeferredItem<Item> CLUMPED_DIAMOND;
	public static final DeferredItem<Item> CLEAR_DIAMOND;
	public static final DeferredItem<Item> CRYSTALIZED_DIAMOND;
	public static final DeferredItem<Item> FLESH_IRON;
	public static final DeferredItem<Item> CRYSTAL_IRON;
	public static final DeferredItem<Item> ROCK_IRON;
	public static final DeferredItem<Item> CLUMP_IRON;
	public static final DeferredItem<Item> SHARD_IRON;
	public static final DeferredItem<Item> DUST_IRON;
	public static final DeferredItem<Item> HEX_IRON;
	public static final DeferredItem<Item> GEM_IRON;
	public static final DeferredItem<Item> GLOSSY_INGOT_IRON;
	public static final DeferredItem<Item> ROUGH_INGOT_IRON;
	public static final DeferredItem<Item> SHINY_INGOT_IRON;
	public static final DeferredItem<Item> FLESH_DIAMOND;
	public static final DeferredItem<Item> CRYSTAL_DIAMOND;
	public static final DeferredItem<Item> ROCK_DIAMOND;
	public static final DeferredItem<Item> CLUMP_DIAMOND;
	public static final DeferredItem<Item> SHARD_DIAMOND;
	public static final DeferredItem<Item> DUST_DIAMOND;
	public static final DeferredItem<Item> HEX_DIAMOND;
	public static final DeferredItem<Item> CLEAR_INGOT_DIAMOND;
	public static final DeferredItem<Item> GLOSSY_INGOT_DIAMOND;
	public static final DeferredItem<Item> ROUGH_INGOT_DIAMOND;
	public static final DeferredItem<Item> SHINY_INGOT_DIAMOND;
	public static final DeferredItem<Item> CLEAR_INGOT_NETHERITE;
	public static final DeferredItem<Item> FLESH_NETHERITE;
	public static final DeferredItem<Item> CRYSTAL_NETHERITE;
	public static final DeferredItem<Item> ROCK_NETHERITE;
	public static final DeferredItem<Item> CLUMP_NETHERITE;
	public static final DeferredItem<Item> SHARD_NETHERITE;
	public static final DeferredItem<Item> DUST_NETHERITE;
	public static final DeferredItem<Item> HEX_NETHERITE;
	public static final DeferredItem<Item> GLOSSY_INGOT_NETHERITE;
	public static final DeferredItem<Item> GEM_NETHERITE;
	public static final DeferredItem<Item> SHINY_INGOT_NETHERITE;
	public static final DeferredItem<Item> CLEAR_INGOT_COPPER;
	public static final DeferredItem<Item> FLESH_COPPER;
	public static final DeferredItem<Item> CRYSTAL_COPPER;
	public static final DeferredItem<Item> ROCK_COPPER;
	public static final DeferredItem<Item> CLUMP_COPPER;
	public static final DeferredItem<Item> SHARD_COPPER;
	public static final DeferredItem<Item> DUST_COPPER;
	public static final DeferredItem<Item> HEX_COPPER;
	public static final DeferredItem<Item> ROUGH_INGOT_COPPER;
	public static final DeferredItem<Item> GEM_COPPER;
	public static final DeferredItem<Item> SHINY_INGOT_COPPER;
	public static final DeferredItem<Item> CLEAR_INGOT_REDSTONE;
	public static final DeferredItem<Item> FLESH_REDSTONE;
	public static final DeferredItem<Item> CRYSTAL_REDSTONE;
	public static final DeferredItem<Item> ROCK_REDSTONE;
	public static final DeferredItem<Item> CLUMP_REDSTONE;
	public static final DeferredItem<Item> SHARD_REDSTONE;
	public static final DeferredItem<Item> GLOSSY_INGOT_REDSTONE;
	public static final DeferredItem<Item> HEX_REDSTONE;
	public static final DeferredItem<Item> ROUGH_INGOT_REDSTONE;
	public static final DeferredItem<Item> GEM_REDSTONE;
	public static final DeferredItem<Item> SHINY_INGOT_REDSTONE;
	public static final DeferredItem<Item> CLEAR_INGOT_LAPIS_LAZULI;
	public static final DeferredItem<Item> DUST_LAPIS_LAZULI;
	public static final DeferredItem<Item> CRYSTAL_LAPIS_LAZULI;
	public static final DeferredItem<Item> ROCK_LAPIS_LAZULI;
	public static final DeferredItem<Item> CLUMP_LAPIS_LAZULI;
	public static final DeferredItem<Item> SHARD_LAPIS_LAZULI;
	public static final DeferredItem<Item> GLOSSY_INGOT_LAPIS_LAZULI;
	public static final DeferredItem<Item> HEX_LAPIS_LAZULI;
	public static final DeferredItem<Item> ROUGH_INGOT_LAPIS_LAZULI;
	public static final DeferredItem<Item> GEM_LAPIS_LAZULI;
	public static final DeferredItem<Item> SHINY_INGOT_LAPIS_LAZULI;
	public static final DeferredItem<Item> CLEAR_INGOT_COAL;
	public static final DeferredItem<Item> DUST_COAL;
	public static final DeferredItem<Item> CRYSTAL_COAL;
	public static final DeferredItem<Item> FLESH_COAL;
	public static final DeferredItem<Item> CLUMP_COAL;
	public static final DeferredItem<Item> SHARD_COAL;
	public static final DeferredItem<Item> GLOSSY_INGOT_COAL;
	public static final DeferredItem<Item> HEX_COAL;
	public static final DeferredItem<Item> ROUGH_INGOT_COAL;
	public static final DeferredItem<Item> GEM_COAL;
	public static final DeferredItem<Item> SHINY_INGOT_COAL;
	public static final DeferredItem<Item> CLEAR_INGOT_RESIN;
	public static final DeferredItem<Item> DUST_RESIN;
	public static final DeferredItem<Item> CRYSTAL_RESIN;
	public static final DeferredItem<Item> FLESH_RESIN;
	public static final DeferredItem<Item> ROCK_RESIN;
	public static final DeferredItem<Item> SHARD_RESIN;
	public static final DeferredItem<Item> GLOSSY_INGOT_RESIN;
	public static final DeferredItem<Item> HEX_RESIN;
	public static final DeferredItem<Item> ROUGH_INGOT_RESIN;
	public static final DeferredItem<Item> GEM_RESIN;
	public static final DeferredItem<Item> SHINY_INGOT_RESIN;
	public static final DeferredItem<Item> CLEAR_INGOT_QUARTZ;
	public static final DeferredItem<Item> DUST_QUARTZ;
	public static final DeferredItem<Item> CLUMP_QUARTZ;
	public static final DeferredItem<Item> FLESH_QUARTZ;
	public static final DeferredItem<Item> ROCK_QUARTZ;
	public static final DeferredItem<Item> SHARD_QUARTZ;
	public static final DeferredItem<Item> GLOSSY_INGOT_QUARTZ;
	public static final DeferredItem<Item> HEX_QUARTZ;
	public static final DeferredItem<Item> ROUGH_INGOT_QUARTZ;
	public static final DeferredItem<Item> GEM_QUARTZ;
	public static final DeferredItem<Item> SHINY_INGOT_QUARTZ;
	public static final DeferredItem<Item> CLEAR_INGOT_AMETHYST;
	public static final DeferredItem<Item> DUST_AMETHYST;
	public static final DeferredItem<Item> CLUMP_AMETHYST;
	public static final DeferredItem<Item> FLESH_AMETHYST;
	public static final DeferredItem<Item> ROCK_AMETHYST;
	public static final DeferredItem<Item> CRYSTAL_AMETHYST;
	public static final DeferredItem<Item> GLOSSY_INGOT_AMETHYST;
	public static final DeferredItem<Item> HEX_AMETHYST;
	public static final DeferredItem<Item> ROUGH_INGOT_AMETHYST;
	public static final DeferredItem<Item> GEM_AMETHYST;
	public static final DeferredItem<Item> SHINY_INGOT_AMETHYST;
	public static final DeferredItem<Item> CLEAR_INGOT_EMERALD;
	public static final DeferredItem<Item> DUST_EMERALD;
	public static final DeferredItem<Item> CLUMP_EMERALD;
	public static final DeferredItem<Item> FLESH_EMERALD;
	public static final DeferredItem<Item> ROCK_EMERALD;
	public static final DeferredItem<Item> CRYSTAL_EMERALD;
	public static final DeferredItem<Item> GLOSSY_INGOT_EMERALD;
	public static final DeferredItem<Item> SHARD_EMERALD;
	public static final DeferredItem<Item> ROUGH_INGOT_EMERALD;
	public static final DeferredItem<Item> GEM_EMERALD;
	public static final DeferredItem<Item> SHINY_INGOT_EMERALD;
	public static final DeferredItem<Item> CLEAR_INGOT_GOLD;
	public static final DeferredItem<Item> DUST_GOLD;
	public static final DeferredItem<Item> CLUMP_GOLD;
	public static final DeferredItem<Item> FLESH_GOLD;
	public static final DeferredItem<Item> ROCK_GOLD;
	public static final DeferredItem<Item> CRYSTAL_GOLD;
	public static final DeferredItem<Item> GLOSSY_INGOT_GOLD;
	public static final DeferredItem<Item> SHARD_GOLD;
	public static final DeferredItem<Item> ROUGH_INGOT_GOLD;
	public static final DeferredItem<Item> GEM_GOLD;
	public static final DeferredItem<Item> HEX_GOLD;
	public static final DeferredItem<Item> RAW_NETHERITE;
	public static final DeferredItem<Item> BASALT_NETHERITE_ORE;
	public static final DeferredItem<Item> BONE_BLOCK_NETHERITE_ORE;
	public static final DeferredItem<Item> NETHERITE_COMPASS;
	public static final DeferredItem<Item> NETHERITE_CLOCK;
	public static final DeferredItem<Item> GOLDEN_UPGRADE;
	public static final DeferredItem<Item> GOLDEN_COMPASS;
	public static final DeferredItem<Item> COPPER_UPGRADE;
	public static final DeferredItem<Item> IRON_UPGRADE;
	public static final DeferredItem<Item> COPPER_COMPASS;
	public static final DeferredItem<Item> COPPER_CLOCK;
	public static final DeferredItem<Item> IRON_CLOCK;
	public static final DeferredItem<Item> COPPER_CAMPFIRE;
	public static final DeferredItem<Item> COPPER_NAME_TAG;
	public static final DeferredItem<Item> GOLDEN_NAME_TAG;
	public static final DeferredItem<Item> NETHERITE_NAME_TAG;
	public static final DeferredItem<Item> PRISMARINE_ORE;
	public static final DeferredItem<Item> DEEPSLATE_PRISMARINE_ORE;
	public static final DeferredItem<Item> BEVELED_PRISMARINE;
	public static final DeferredItem<Item> CLUMPED_PRISMARINE;
	public static final DeferredItem<Item> CLEAR_PRISMARINE;
	public static final DeferredItem<Item> CRYSTALIZED_PRISMARINE;
	public static final DeferredItem<Item> BOLTED_PRISMARINE;
	public static final DeferredItem<Item> STONY_PRISMARINE;
	public static final DeferredItem<Item> ROUGH_PRISMARINE;
	public static final DeferredItem<Item> METALLIC_PRISMARINE;
	public static final DeferredItem<Item> GLOSSY_PRISMARINE;
	public static final DeferredItem<Item> POWDERED_PRISMARINE;
	public static final DeferredItem<Item> SPECKLED_PRISMARINE;
	public static final DeferredItem<Item> CLEAR_INGOT_PRISMARINE;
	public static final DeferredItem<Item> SHINY_INGOT_PRISMARINE;
	public static final DeferredItem<Item> GLOSSY_INGOT_PRISMARINE;
	public static final DeferredItem<Item> ROUGH_INGOT_PRISMARINE;
	public static final DeferredItem<Item> DUST_PRISMARINE;
	public static final DeferredItem<Item> CLUMP_PRISMARINE;
	public static final DeferredItem<Item> FLESH_PRISMARINE;
	public static final DeferredItem<Item> ROCK_PRISMARINE;
	public static final DeferredItem<Item> CRYSTAL_PRISMARINE;
	public static final DeferredItem<Item> SHARD_PRISMARINE;
	public static final DeferredItem<Item> GEM_PRISMARINE;
	public static final DeferredItem<Item> HEX_PRISMARINE;
	public static final DeferredItem<Item> GLASS_AMETHYST;
	public static final DeferredItem<Item> GLASS_COAL;
	public static final DeferredItem<Item> GLASS_COPPER;
	public static final DeferredItem<Item> GLASS_DIAMOND;
	public static final DeferredItem<Item> GLASS_EMERALD;
	public static final DeferredItem<Item> GLASS_GOLD;
	public static final DeferredItem<Item> GLASS_IRON;
	public static final DeferredItem<Item> GLASS_LAPIS_LAZULI;
	public static final DeferredItem<Item> GLASS_NETHERITE;
	public static final DeferredItem<Item> GLASS_QUARTZ;
	public static final DeferredItem<Item> GLASS_REDSTONE;
	public static final DeferredItem<Item> GLASS_RESIN;
	public static final DeferredItem<Item> HUE_AMETHYST;
	public static final DeferredItem<Item> HUE_COAL;
	public static final DeferredItem<Item> HUE_COPPER;
	public static final DeferredItem<Item> HUE_DIAMOND;
	public static final DeferredItem<Item> HUE_EMERALD;
	public static final DeferredItem<Item> HUE_GOLD;
	public static final DeferredItem<Item> HUE_IRON;
	public static final DeferredItem<Item> HUE_LAPIS_LAZULI;
	public static final DeferredItem<Item> HUE_NETHERITE;
	public static final DeferredItem<Item> HUE_QUARTZ;
	public static final DeferredItem<Item> HUE_REDSTONE;
	public static final DeferredItem<Item> HUE_RESIN;
	public static final DeferredItem<Item> PRISMARINE_SWORD;
	public static final DeferredItem<Item> PRISMARINE_AXE;
	public static final DeferredItem<Item> PRISMARINE_PICKAXE;
	public static final DeferredItem<Item> PRISMARINE_SHOVEL;
	public static final DeferredItem<Item> PRISMARINE_HOE;
	public static final DeferredItem<Item> PRISMARINE_HELMET;
	public static final DeferredItem<Item> PRISMARINE_CHESTPLATE;
	public static final DeferredItem<Item> PRISMARINE_LEGGINGS;
	public static final DeferredItem<Item> PRISMARINE_BOOTS;
	public static final DeferredItem<Item> MYSTERY_ORE;
	public static final DeferredItem<Item> DEEPSLATE_MYSTERY_ORE;
	public static final DeferredItem<Item> ORES_AND_TIERS_ICON;
	static {
		REDSTONE_ARMOR_HELMET = register("redstone_armor_helmet", RedstoneArmorItem.Helmet::new);
		REDSTONE_ARMOR_CHESTPLATE = register("redstone_armor_chestplate", RedstoneArmorItem.Chestplate::new);
		REDSTONE_ARMOR_LEGGINGS = register("redstone_armor_leggings", RedstoneArmorItem.Leggings::new);
		REDSTONE_ARMOR_BOOTS = register("redstone_armor_boots", RedstoneArmorItem.Boots::new);
		LAPIS_LAZULI_ARMOR_HELMET = register("lapis_lazuli_armor_helmet", LapisLazuliArmorItem.Helmet::new);
		LAPIS_LAZULI_ARMOR_CHESTPLATE = register("lapis_lazuli_armor_chestplate", LapisLazuliArmorItem.Chestplate::new);
		LAPIS_LAZULI_ARMOR_LEGGINGS = register("lapis_lazuli_armor_leggings", LapisLazuliArmorItem.Leggings::new);
		LAPIS_LAZULI_ARMOR_BOOTS = register("lapis_lazuli_armor_boots", LapisLazuliArmorItem.Boots::new);
		EMERALD_ARMOR_HELMET = register("emerald_armor_helmet", EmeraldArmorItem.Helmet::new);
		EMERALD_ARMOR_CHESTPLATE = register("emerald_armor_chestplate", EmeraldArmorItem.Chestplate::new);
		EMERALD_ARMOR_LEGGINGS = register("emerald_armor_leggings", EmeraldArmorItem.Leggings::new);
		EMERALD_ARMOR_BOOTS = register("emerald_armor_boots", EmeraldArmorItem.Boots::new);
		AMETHYST_ARMOR_HELMET = register("amethyst_armor_helmet", AmethystArmorItem.Helmet::new);
		AMETHYST_ARMOR_CHESTPLATE = register("amethyst_armor_chestplate", AmethystArmorItem.Chestplate::new);
		AMETHYST_ARMOR_LEGGINGS = register("amethyst_armor_leggings", AmethystArmorItem.Leggings::new);
		AMETHYST_ARMOR_BOOTS = register("amethyst_armor_boots", AmethystArmorItem.Boots::new);
		QUARTZ_ARMOR_HELMET = register("quartz_armor_helmet", QuartzArmorItem.Helmet::new);
		QUARTZ_ARMOR_CHESTPLATE = register("quartz_armor_chestplate", QuartzArmorItem.Chestplate::new);
		QUARTZ_ARMOR_LEGGINGS = register("quartz_armor_leggings", QuartzArmorItem.Leggings::new);
		QUARTZ_ARMOR_BOOTS = register("quartz_armor_boots", QuartzArmorItem.Boots::new);
		RESIN_ARMOR_HELMET = register("resin_armor_helmet", ResinArmorItem.Helmet::new);
		RESIN_ARMOR_CHESTPLATE = register("resin_armor_chestplate", ResinArmorItem.Chestplate::new);
		RESIN_ARMOR_LEGGINGS = register("resin_armor_leggings", ResinArmorItem.Leggings::new);
		RESIN_ARMOR_BOOTS = register("resin_armor_boots", ResinArmorItem.Boots::new);
		REDSTONE_SWORD = register("redstone_sword", RedstoneSwordItem::new);
		REDSTONE_AXE = register("redstone_axe", RedstoneAxeItem::new);
		REDSTONE_HOE = register("redstone_hoe", RedstoneHoeItem::new);
		REDSTONE_PICKAXE = register("redstone_pickaxe", RedstonePickaxeItem::new);
		REDSTONE_SHOVEL = register("redstone_shovel", RedstoneShovelItem::new);
		RESIN_BULB_LIT = block(ZingsOresAndTiersModBlocks.RESIN_BULB_LIT);
		RESIN_BULB = block(ZingsOresAndTiersModBlocks.RESIN_BULB);
		RESIN_LANTERN = block(ZingsOresAndTiersModBlocks.RESIN_LANTERN);
		RESIN_TORCH = block(ZingsOresAndTiersModBlocks.RESIN_TORCH);
		GOLDEN_LANTERN = block(ZingsOresAndTiersModBlocks.GOLDEN_LANTERN);
		GOLDEN_TORCH = block(ZingsOresAndTiersModBlocks.GOLDEN_TORCH);
		NETHERITE_NUGGET = register("netherite_nugget", NetheriteNuggetItem::new);
		IRON_LANTERN = block(ZingsOresAndTiersModBlocks.IRON_LANTERN);
		IRON_TORCH = block(ZingsOresAndTiersModBlocks.IRON_TORCH);
		NETHERITE_LANTERN = block(ZingsOresAndTiersModBlocks.NETHERITE_LANTERN);
		NETHERITE_TORCH = block(ZingsOresAndTiersModBlocks.NETHERITE_TORCH);
		WARPED_NETHERITE_LANTERN = block(ZingsOresAndTiersModBlocks.WARPED_NETHERITE_LANTERN);
		WARPED_NETHERITE_TORCH = block(ZingsOresAndTiersModBlocks.WARPED_NETHERITE_TORCH);
		CRIMSON_NETHERITE_LANTERN = block(ZingsOresAndTiersModBlocks.CRIMSON_NETHERITE_LANTERN);
		CRIMSON_NETHERITE_TORCH = block(ZingsOresAndTiersModBlocks.CRIMSON_NETHERITE_TORCH);
		NETHERITE_LIGHTNING_ROD = block(ZingsOresAndTiersModBlocks.NETHERITE_LIGHTNING_ROD);
		GOLDEN_LIGHTNING_ROD = block(ZingsOresAndTiersModBlocks.GOLDEN_LIGHTNING_ROD);
		IRON_LIGHTNING_ROD = block(ZingsOresAndTiersModBlocks.IRON_LIGHTNING_ROD);
		NETHERITE_CHAIN = block(ZingsOresAndTiersModBlocks.NETHERITE_CHAIN);
		GOLDEN_CHAIN = block(ZingsOresAndTiersModBlocks.GOLDEN_CHAIN);
		NETHERITE_BULB = block(ZingsOresAndTiersModBlocks.NETHERITE_BULB);
		CRIMSON_NETHERITE_BULB = block(ZingsOresAndTiersModBlocks.CRIMSON_NETHERITE_BULB);
		WARPED_NETHERITE_BULB = block(ZingsOresAndTiersModBlocks.WARPED_NETHERITE_BULB);
		NETHERITE_BULB_LIT = block(ZingsOresAndTiersModBlocks.NETHERITE_BULB_LIT);
		CRIMSON_NETHERITE_BULB_LIT = block(ZingsOresAndTiersModBlocks.CRIMSON_NETHERITE_BULB_LIT);
		WARPED_NETHERITE_BULB_LIT = block(ZingsOresAndTiersModBlocks.WARPED_NETHERITE_BULB_LIT);
		BOLTED_NETHERITE = block(ZingsOresAndTiersModBlocks.BOLTED_NETHERITE);
		NETHERITE_RAIL = block(ZingsOresAndTiersModBlocks.NETHERITE_RAIL);
		NETHERITE_TRAPDOOR = block(ZingsOresAndTiersModBlocks.NETHERITE_TRAPDOOR);
		NETHERITE_GRATE = block(ZingsOresAndTiersModBlocks.NETHERITE_GRATE);
		CUT_NETHERITE = block(ZingsOresAndTiersModBlocks.CUT_NETHERITE);
		CUT_NETHERITE_STAIRS = block(ZingsOresAndTiersModBlocks.CUT_NETHERITE_STAIRS);
		CUT_NETHERITE_SLAB = block(ZingsOresAndTiersModBlocks.CUT_NETHERITE_SLAB);
		NETHERITE_BARS = block(ZingsOresAndTiersModBlocks.NETHERITE_BARS);
		NETHERITE_DOOR = doubleBlock(ZingsOresAndTiersModBlocks.NETHERITE_DOOR);
		CUT_IRON = block(ZingsOresAndTiersModBlocks.CUT_IRON);
		BOLTED_IRON = block(ZingsOresAndTiersModBlocks.BOLTED_IRON);
		CUT_GOLD = block(ZingsOresAndTiersModBlocks.CUT_GOLD);
		BOLTED_GOLD = block(ZingsOresAndTiersModBlocks.BOLTED_GOLD);
		IRON_BRUSH = register("iron_brush", IronBrushItem::new);
		NETHERITE_BRUSH = register("netherite_brush", NetheriteBrushItem::new);
		GOLDEN_BRUSH = register("golden_brush", GoldenBrushItem::new);
		GOLDEN_SHEARS = register("golden_shears", GoldenShearsItem::new);
		COPPER_SHEARS = register("copper_shears", CopperShearsItem::new);
		NETHERITE_SHEARS = register("netherite_shears", NetheriteShearsItem::new);
		GOLDEN_BUCKET = register("golden_bucket", GoldenBucketItem::new);
		COPPER_BUCKET = register("copper_bucket", CopperBucketItem::new);
		NETHERITE_BUCKET = register("netherite_bucket", NetheriteBucketItem::new);
		GOLDEN_WATER_BUCKET = register("golden_water_bucket", GoldenWaterBucketItem::new);
		COPPER_WATER_BUCKET = register("copper_water_bucket", CopperWaterBucketItem::new);
		NETHERITE_WATER_BUCKET = register("netherite_water_bucket", NetheriteWaterBucketItem::new);
		GOLDEN_LAVA_BUCKET = register("golden_lava_bucket", GoldenLavaBucketItem::new);
		NETHERITE_LAVA_BUCKET = register("netherite_lava_bucket", NetheriteLavaBucketItem::new);
		COPPER_LAVA_BUCKET = register("copper_lava_bucket", CopperLavaBucketItem::new);
		COPPER_SCRAP = register("copper_scrap", CopperScrapItem::new);
		GOLDEN_SCRAP = register("golden_scrap", GoldenScrapItem::new);
		IRON_SCRAP = register("iron_scrap", IronScrapItem::new);
		FLINT_AND_NETHERITE = register("flint_and_netherite", FlintAndNetheriteItem::new);
		FLINT_AND_GOLD = register("flint_and_gold", FlintAndGoldItem::new);
		FLINT_AND_COPPER = register("flint_and_copper", FlintAndCopperItem::new);
		GOLDEN_BARS = block(ZingsOresAndTiersModBlocks.GOLDEN_BARS);
		GOLDEN_TRAPDOOR = block(ZingsOresAndTiersModBlocks.GOLDEN_TRAPDOOR);
		GOLDEN_DOOR = doubleBlock(ZingsOresAndTiersModBlocks.GOLDEN_DOOR);
		GOLDEN_GRATE = block(ZingsOresAndTiersModBlocks.GOLDEN_GRATE);
		IRON_GRATE = block(ZingsOresAndTiersModBlocks.IRON_GRATE);
		COPPER_RAIL = block(ZingsOresAndTiersModBlocks.COPPER_RAIL);
		GOLDEN_RAIL = block(ZingsOresAndTiersModBlocks.GOLDEN_RAIL);
		GOLDEN_BULB = block(ZingsOresAndTiersModBlocks.GOLDEN_BULB);
		IRON_BULB = block(ZingsOresAndTiersModBlocks.IRON_BULB);
		IRON_BULB_LIT = block(ZingsOresAndTiersModBlocks.IRON_BULB_LIT);
		GOLDEN_BULB_LIT = block(ZingsOresAndTiersModBlocks.GOLDEN_BULB_LIT);
		LAPIS_LAZULI_SWORD = register("lapis_lazuli_sword", LapisLazuliSwordItem::new);
		EMERALD_SWORD = register("emerald_sword", EmeraldSwordItem::new);
		QUARTZ_SWORD = register("quartz_sword", QuartzSwordItem::new);
		AMETHYST_SWORD = register("amethyst_sword", AmethystSwordItem::new);
		RESIN_SWORD = register("resin_sword", ResinSwordItem::new);
		LAPIS_LAZULI_AXE = register("lapis_lazuli_axe", LapisLazuliAxeItem::new);
		EMERALD_AXE = register("emerald_axe", EmeraldAxeItem::new);
		QUARTZ_AXE = register("quartz_axe", QuartzAxeItem::new);
		AMETHYST_AXE = register("amethyst_axe", AmethystAxeItem::new);
		RESIN_AXE = register("resin_axe", ResinAxeItem::new);
		LAPIS_LAZULI_HOE = register("lapis_lazuli_hoe", LapisLazuliHoeItem::new);
		EMERALD_HOE = register("emerald_hoe", EmeraldHoeItem::new);
		QUARTZ_HOE = register("quartz_hoe", QuartzHoeItem::new);
		AMETHYST_HOE = register("amethyst_hoe", AmethystHoeItem::new);
		RESIN_HOE = register("resin_hoe", ResinHoeItem::new);
		LAPIS_LAZULI_PICKAXE = register("lapis_lazuli_pickaxe", LapisLazuliPickaxeItem::new);
		EMERALD_PICKAXE = register("emerald_pickaxe", EmeraldPickaxeItem::new);
		QUARTZ_PICKAXE = register("quartz_pickaxe", QuartzPickaxeItem::new);
		AMETHYST_PICKAXE = register("amethyst_pickaxe", AmethystPickaxeItem::new);
		RESIN_PICKAXE = register("resin_pickaxe", ResinPickaxeItem::new);
		LAPIS_LAZULI_SHOVEL = register("lapis_lazuli_shovel", LapisLazuliShovelItem::new);
		EMERALD_SHOVEL = register("emerald_shovel", EmeraldShovelItem::new);
		QUARTZ_SHOVEL = register("quartz_shovel", QuartzShovelItem::new);
		AMETHYST_SHOVEL = register("amethyst_shovel", AmethystShovelItem::new);
		RESIN_SHOVEL = register("resin_shovel", ResinShovelItem::new);
		REDSTONE_UPGRADE = register("redstone_upgrade", RedstoneUpgradeItem::new);
		LAPIS_LAZULI_UPGRADE = register("lapis_lazuli_upgrade", LapisLazuliUpgradeItem::new);
		AMETHYST_ORE = block(ZingsOresAndTiersModBlocks.AMETHYST_ORE);
		RESIN_ORE = block(ZingsOresAndTiersModBlocks.RESIN_ORE);
		QUARTZ_ORE = block(ZingsOresAndTiersModBlocks.QUARTZ_ORE);
		DEEPSLATE_QUARTZ_ORE = block(ZingsOresAndTiersModBlocks.DEEPSLATE_QUARTZ_ORE);
		DEEPSLATE_AMETHYST_ORE = block(ZingsOresAndTiersModBlocks.DEEPSLATE_AMETHYST_ORE);
		DEEPSLATE_RESIN_ORE = block(ZingsOresAndTiersModBlocks.DEEPSLATE_RESIN_ORE);
		ANDESITE_AMETHYST_ORE = block(ZingsOresAndTiersModBlocks.ANDESITE_AMETHYST_ORE);
		DIORITE_AMETHYST_ORE = block(ZingsOresAndTiersModBlocks.DIORITE_AMETHYST_ORE);
		GRANITE_AMETHYST_ORE = block(ZingsOresAndTiersModBlocks.GRANITE_AMETHYST_ORE);
		TUFF_AMETHYST_ORE = block(ZingsOresAndTiersModBlocks.TUFF_AMETHYST_ORE);
		ANDESITE_RESIN_ORE = block(ZingsOresAndTiersModBlocks.ANDESITE_RESIN_ORE);
		DIORITE_RESIN_ORE = block(ZingsOresAndTiersModBlocks.DIORITE_RESIN_ORE);
		GRANITE_RESIN_ORE = block(ZingsOresAndTiersModBlocks.GRANITE_RESIN_ORE);
		TUFF_RESIN_ORE = block(ZingsOresAndTiersModBlocks.TUFF_RESIN_ORE);
		ANDESITE_QUARTZ_ORE = block(ZingsOresAndTiersModBlocks.ANDESITE_QUARTZ_ORE);
		DIORITE_QUARTZ_ORE = block(ZingsOresAndTiersModBlocks.DIORITE_QUARTZ_ORE);
		GRANITE_QUARTZ_ORE = block(ZingsOresAndTiersModBlocks.GRANITE_QUARTZ_ORE);
		TUFF_QUARTZ_ORE = block(ZingsOresAndTiersModBlocks.TUFF_QUARTZ_ORE);
		CLAY_AMETHYST_ORE = block(ZingsOresAndTiersModBlocks.CLAY_AMETHYST_ORE);
		CALCITE_AMETHYST_ORE = block(ZingsOresAndTiersModBlocks.CALCITE_AMETHYST_ORE);
		BASALT_AMETHYST_ORE = block(ZingsOresAndTiersModBlocks.BASALT_AMETHYST_ORE);
		PALE_MOSS_RESIN_ORE = block(ZingsOresAndTiersModBlocks.PALE_MOSS_RESIN_ORE);
		BASALT_QUARTZ_ORE = block(ZingsOresAndTiersModBlocks.BASALT_QUARTZ_ORE);
		ANDESITE_DIAMOND_ORE = block(ZingsOresAndTiersModBlocks.ANDESITE_DIAMOND_ORE);
		ANDESITE_COAL_ORE = block(ZingsOresAndTiersModBlocks.ANDESITE_COAL_ORE);
		ANDESITE_REDSTONE_ORE = block(ZingsOresAndTiersModBlocks.ANDESITE_REDSTONE_ORE);
		ANDESITE_EMERALD_ORE = block(ZingsOresAndTiersModBlocks.ANDESITE_EMERALD_ORE);
		ANDESITE_GOLD_ORE = block(ZingsOresAndTiersModBlocks.ANDESITE_GOLD_ORE);
		ANDESITE_IRON_ORE = block(ZingsOresAndTiersModBlocks.ANDESITE_IRON_ORE);
		ANDESITE_LAPIS_LAZULI_ORE = block(ZingsOresAndTiersModBlocks.ANDESITE_LAPIS_LAZULI_ORE);
		ANDESITE_COPPER_ORE = block(ZingsOresAndTiersModBlocks.ANDESITE_COPPER_ORE);
		DIORITE_DIAMOND_ORE = block(ZingsOresAndTiersModBlocks.DIORITE_DIAMOND_ORE);
		GRANITE_DIAMOND_ORE = block(ZingsOresAndTiersModBlocks.GRANITE_DIAMOND_ORE);
		OBSIDIAN_DIAMOND_ORE = block(ZingsOresAndTiersModBlocks.OBSIDIAN_DIAMOND_ORE);
		TUFF_DIAMOND_ORE = block(ZingsOresAndTiersModBlocks.TUFF_DIAMOND_ORE);
		SANDSTONE_DIAMOND_ORE = block(ZingsOresAndTiersModBlocks.SANDSTONE_DIAMOND_ORE);
		DIORITE_EMERALD_ORE = block(ZingsOresAndTiersModBlocks.DIORITE_EMERALD_ORE);
		GRANITE_EMERALD_ORE = block(ZingsOresAndTiersModBlocks.GRANITE_EMERALD_ORE);
		TUFF_EMERALD_ORE = block(ZingsOresAndTiersModBlocks.TUFF_EMERALD_ORE);
		SANDSTONE_EMERALD_ORE = block(ZingsOresAndTiersModBlocks.SANDSTONE_EMERALD_ORE);
		GRANITE_COAL_ORE = block(ZingsOresAndTiersModBlocks.GRANITE_COAL_ORE);
		DIORITE_COAL_ORE = block(ZingsOresAndTiersModBlocks.DIORITE_COAL_ORE);
		TUFF_COAL_ORE = block(ZingsOresAndTiersModBlocks.TUFF_COAL_ORE);
		SANDSTONE_COAL_ORE = block(ZingsOresAndTiersModBlocks.SANDSTONE_COAL_ORE);
		DIORITE_GOLD_ORE = block(ZingsOresAndTiersModBlocks.DIORITE_GOLD_ORE);
		GRANITE_GOLD_ORE = block(ZingsOresAndTiersModBlocks.GRANITE_GOLD_ORE);
		TUFF_GOLD_ORE = block(ZingsOresAndTiersModBlocks.TUFF_GOLD_ORE);
		SANDSTONE_GOLD_ORE = block(ZingsOresAndTiersModBlocks.SANDSTONE_GOLD_ORE);
		TERRACOTTA_GOLD_ORE = block(ZingsOresAndTiersModBlocks.TERRACOTTA_GOLD_ORE);
		BASALT_GOLD_ORE = block(ZingsOresAndTiersModBlocks.BASALT_GOLD_ORE);
		RED_SANDSTONE_GOLD_ORE = block(ZingsOresAndTiersModBlocks.RED_SANDSTONE_GOLD_ORE);
		TUFF_IRON_ORE = block(ZingsOresAndTiersModBlocks.TUFF_IRON_ORE);
		SANDSTONE_IRON_ORE = block(ZingsOresAndTiersModBlocks.SANDSTONE_IRON_ORE);
		GRANITE_IRON_ORE = block(ZingsOresAndTiersModBlocks.GRANITE_IRON_ORE);
		DIORITE_IRON_ORE = block(ZingsOresAndTiersModBlocks.DIORITE_IRON_ORE);
		DIORITE_COPPER_ORE = block(ZingsOresAndTiersModBlocks.DIORITE_COPPER_ORE);
		GRANITE_COPPER_ORE = block(ZingsOresAndTiersModBlocks.GRANITE_COPPER_ORE);
		TUFF_COPPER_ORE = block(ZingsOresAndTiersModBlocks.TUFF_COPPER_ORE);
		DRIPSTONE_COPPER_ORE = block(ZingsOresAndTiersModBlocks.DRIPSTONE_COPPER_ORE);
		DIORITE_REDSTONE_ORE = block(ZingsOresAndTiersModBlocks.DIORITE_REDSTONE_ORE);
		GRANITE_REDSTONE_ORE = block(ZingsOresAndTiersModBlocks.GRANITE_REDSTONE_ORE);
		SANDSTONE_REDSTONE_ORE = block(ZingsOresAndTiersModBlocks.SANDSTONE_REDSTONE_ORE);
		TUFF_REDSTONE_ORE = block(ZingsOresAndTiersModBlocks.TUFF_REDSTONE_ORE);
		DIORITE_LAPIS_LAZULI_ORE = block(ZingsOresAndTiersModBlocks.DIORITE_LAPIS_LAZULI_ORE);
		GRANITE_LAPIS_LAZULI_ORE = block(ZingsOresAndTiersModBlocks.GRANITE_LAPIS_LAZULI_ORE);
		SANDSTONE_LAPIS_LAZULI_ORE = block(ZingsOresAndTiersModBlocks.SANDSTONE_LAPIS_LAZULI_ORE);
		TUFF_LAPIS_LAZULI_ORE = block(ZingsOresAndTiersModBlocks.TUFF_LAPIS_LAZULI_ORE);
		GOLDEN_GOLEM_SPAWN_EGG = register("golden_golem_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(ZingsOresAndTiersModEntities.GOLDEN_GOLEM.get())));
		NETHERITE_GOLEM_SPAWN_EGG = register("netherite_golem_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(ZingsOresAndTiersModEntities.NETHERITE_GOLEM.get())));
		ZING_BOOK_VOLUME_SIX = register("zing_book_volume_six", ZingBookVolumeSixItem::new);
		COPPER_DANDELION = block(ZingsOresAndTiersModBlocks.COPPER_DANDELION);
		NETHERITE_DANDELION = block(ZingsOresAndTiersModBlocks.NETHERITE_DANDELION);
		IRON_DANDELION = block(ZingsOresAndTiersModBlocks.IRON_DANDELION);
		DIAMOND_DANDELION = block(ZingsOresAndTiersModBlocks.DIAMOND_DANDELION);
		EMERALD_WALL = block(ZingsOresAndTiersModBlocks.EMERALD_WALL);
		EMERALD_SLAB = block(ZingsOresAndTiersModBlocks.EMERALD_SLAB);
		EMERALD_STAIRS = block(ZingsOresAndTiersModBlocks.EMERALD_STAIRS);
		COAL_ARMOR_HELMET = register("coal_armor_helmet", CoalArmorItem.Helmet::new);
		COAL_ARMOR_CHESTPLATE = register("coal_armor_chestplate", CoalArmorItem.Chestplate::new);
		COAL_ARMOR_LEGGINGS = register("coal_armor_leggings", CoalArmorItem.Leggings::new);
		COAL_ARMOR_BOOTS = register("coal_armor_boots", CoalArmorItem.Boots::new);
		COAL_PICKAXE = register("coal_pickaxe", CoalPickaxeItem::new);
		COAL_HOE = register("coal_hoe", CoalHoeItem::new);
		COAL_SHOVEL = register("coal_shovel", CoalShovelItem::new);
		COAL_AXE = register("coal_axe", CoalAxeItem::new);
		COAL_SWORD = register("coal_sword", CoalSwordItem::new);
		COAL_WALL = block(ZingsOresAndTiersModBlocks.COAL_WALL);
		COAL_STAIRS = block(ZingsOresAndTiersModBlocks.COAL_STAIRS);
		COAL_SLAB = block(ZingsOresAndTiersModBlocks.COAL_SLAB);
		DIRT_COAL_ORE = block(ZingsOresAndTiersModBlocks.DIRT_COAL_ORE);
		DIRT_GOLD_ORE = block(ZingsOresAndTiersModBlocks.DIRT_GOLD_ORE);
		DIRT_RESIN_ORE = block(ZingsOresAndTiersModBlocks.DIRT_RESIN_ORE);
		BURNT_OUT_TORCH = block(ZingsOresAndTiersModBlocks.BURNT_OUT_TORCH);
		BLOCK_OF_BURNING_COAL = block(ZingsOresAndTiersModBlocks.BLOCK_OF_BURNING_COAL);
		BLOCK_OF_CHARCOAL = block(ZingsOresAndTiersModBlocks.BLOCK_OF_CHARCOAL);
		BUCKET_OF_COAL = register("bucket_of_coal", BucketOfCoalItem::new);
		BURNING_COAL = register("burning_coal", BurningCoalItem::new);
		POWDERED_GOLD = block(ZingsOresAndTiersModBlocks.POWDERED_GOLD);
		CLUMPED_GOLD = block(ZingsOresAndTiersModBlocks.CLUMPED_GOLD);
		METALLIC_GOLD = block(ZingsOresAndTiersModBlocks.METALLIC_GOLD);
		BEVELED_GOLD = block(ZingsOresAndTiersModBlocks.BEVELED_GOLD);
		ROUGH_GOLD = block(ZingsOresAndTiersModBlocks.ROUGH_GOLD);
		SPECKLED_GOLD = block(ZingsOresAndTiersModBlocks.SPECKLED_GOLD);
		CLEAR_GOLD = block(ZingsOresAndTiersModBlocks.CLEAR_GOLD);
		STONY_GOLD = block(ZingsOresAndTiersModBlocks.STONY_GOLD);
		CRYSTALIZED_GOLD = block(ZingsOresAndTiersModBlocks.CRYSTALIZED_GOLD);
		BOLTED_EMERALD = block(ZingsOresAndTiersModBlocks.BOLTED_EMERALD);
		POWDERED_EMERALD = block(ZingsOresAndTiersModBlocks.POWDERED_EMERALD);
		CLUMPED_EMERALD = block(ZingsOresAndTiersModBlocks.CLUMPED_EMERALD);
		METALLIC_EMERALD = block(ZingsOresAndTiersModBlocks.METALLIC_EMERALD);
		GLOSSY_EMERALD = block(ZingsOresAndTiersModBlocks.GLOSSY_EMERALD);
		ROUGH_EMERALD = block(ZingsOresAndTiersModBlocks.ROUGH_EMERALD);
		SPECKLED_EMERALD = block(ZingsOresAndTiersModBlocks.SPECKLED_EMERALD);
		CLEAR_EMERALD = block(ZingsOresAndTiersModBlocks.CLEAR_EMERALD);
		STONY_EMERALD = block(ZingsOresAndTiersModBlocks.STONY_EMERALD);
		CRYSTALIZED_EMERALD = block(ZingsOresAndTiersModBlocks.CRYSTALIZED_EMERALD);
		BEVELED_AMETHYST = block(ZingsOresAndTiersModBlocks.BEVELED_AMETHYST);
		BOLTED_AMETHYST = block(ZingsOresAndTiersModBlocks.BOLTED_AMETHYST);
		POWDERED_AMETHYST = block(ZingsOresAndTiersModBlocks.POWDERED_AMETHYST);
		CLUMPED_AMETHYST = block(ZingsOresAndTiersModBlocks.CLUMPED_AMETHYST);
		METALLIC_AMETHYST = block(ZingsOresAndTiersModBlocks.METALLIC_AMETHYST);
		GLOSSY_AMETHYST = block(ZingsOresAndTiersModBlocks.GLOSSY_AMETHYST);
		ROUGH_AMETHYST = block(ZingsOresAndTiersModBlocks.ROUGH_AMETHYST);
		SPECKLED_AMETHYST = block(ZingsOresAndTiersModBlocks.SPECKLED_AMETHYST);
		CLEAR_AMETHYST = block(ZingsOresAndTiersModBlocks.CLEAR_AMETHYST);
		STONY_AMETHYST = block(ZingsOresAndTiersModBlocks.STONY_AMETHYST);
		BEVELED_QUARTZ = block(ZingsOresAndTiersModBlocks.BEVELED_QUARTZ);
		BOLTED_QUARTZ = block(ZingsOresAndTiersModBlocks.BOLTED_QUARTZ);
		POWDERED_QUARTZ = block(ZingsOresAndTiersModBlocks.POWDERED_QUARTZ);
		CLUMPED_QUARTZ = block(ZingsOresAndTiersModBlocks.CLUMPED_QUARTZ);
		METALLIC_QUARTZ = block(ZingsOresAndTiersModBlocks.METALLIC_QUARTZ);
		GLOSSY_QUARTZ = block(ZingsOresAndTiersModBlocks.GLOSSY_QUARTZ);
		ROUGH_QUARTZ = block(ZingsOresAndTiersModBlocks.ROUGH_QUARTZ);
		SPECKLED_QUARTZ = block(ZingsOresAndTiersModBlocks.SPECKLED_QUARTZ);
		STONY_QUARTZ = block(ZingsOresAndTiersModBlocks.STONY_QUARTZ);
		CRYSTALIZED_QUARTZ = block(ZingsOresAndTiersModBlocks.CRYSTALIZED_QUARTZ);
		BEVELED_RESIN = block(ZingsOresAndTiersModBlocks.BEVELED_RESIN);
		BOLTED_RESIN = block(ZingsOresAndTiersModBlocks.BOLTED_RESIN);
		POWDERED_RESIN = block(ZingsOresAndTiersModBlocks.POWDERED_RESIN);
		METALLIC_RESIN = block(ZingsOresAndTiersModBlocks.METALLIC_RESIN);
		GLOSSY_RESIN = block(ZingsOresAndTiersModBlocks.GLOSSY_RESIN);
		ROUGH_RESIN = block(ZingsOresAndTiersModBlocks.ROUGH_RESIN);
		SPECKLED_RESIN = block(ZingsOresAndTiersModBlocks.SPECKLED_RESIN);
		CLEAR_RESIN = block(ZingsOresAndTiersModBlocks.CLEAR_RESIN);
		STONY_RESIN = block(ZingsOresAndTiersModBlocks.STONY_RESIN);
		CRYSTALIZED_RESIN = block(ZingsOresAndTiersModBlocks.CRYSTALIZED_RESIN);
		TOUGH_COAL = block(ZingsOresAndTiersModBlocks.TOUGH_COAL);
		BEVELED_COAL = block(ZingsOresAndTiersModBlocks.BEVELED_COAL);
		BOLTED_COAL = block(ZingsOresAndTiersModBlocks.BOLTED_COAL);
		POWDERED_COAL = block(ZingsOresAndTiersModBlocks.POWDERED_COAL);
		METALLIC_COAL = block(ZingsOresAndTiersModBlocks.METALLIC_COAL);
		GLOSSY_COAL = block(ZingsOresAndTiersModBlocks.GLOSSY_COAL);
		SPECKLED_COAL = block(ZingsOresAndTiersModBlocks.SPECKLED_COAL);
		CLUMPED_COAL = block(ZingsOresAndTiersModBlocks.CLUMPED_COAL);
		CLEAR_COAL = block(ZingsOresAndTiersModBlocks.CLEAR_COAL);
		CRYSTALIZED_COAL = block(ZingsOresAndTiersModBlocks.CRYSTALIZED_COAL);
		TOUGH_LAPIS_LAZULI = block(ZingsOresAndTiersModBlocks.TOUGH_LAPIS_LAZULI);
		BEVELED_LAPIS_LAZULI = block(ZingsOresAndTiersModBlocks.BEVELED_LAPIS_LAZULI);
		BOLTED_LAPIS_LAZULI = block(ZingsOresAndTiersModBlocks.BOLTED_LAPIS_LAZULI);
		POWDERED_LAPIS_LAZULI = block(ZingsOresAndTiersModBlocks.POWDERED_LAPIS_LAZULI);
		METALLIC_LAPIS_LAZULI = block(ZingsOresAndTiersModBlocks.METALLIC_LAPIS_LAZULI);
		GLOSSY_LAPIS_LAZULI = block(ZingsOresAndTiersModBlocks.GLOSSY_LAPIS_LAZULI);
		STONY_LAPIS_LAZULI = block(ZingsOresAndTiersModBlocks.STONY_LAPIS_LAZULI);
		CLUMPED_LAPIS_LAZULI = block(ZingsOresAndTiersModBlocks.CLUMPED_LAPIS_LAZULI);
		CLEAR_LAPIS_LAZULI = block(ZingsOresAndTiersModBlocks.CLEAR_LAPIS_LAZULI);
		CRYSTALIZED_LAPIS_LAZULI = block(ZingsOresAndTiersModBlocks.CRYSTALIZED_LAPIS_LAZULI);
		TOUGH_REDSTONE = block(ZingsOresAndTiersModBlocks.TOUGH_REDSTONE);
		BEVELED_REDSTONE = block(ZingsOresAndTiersModBlocks.BEVELED_REDSTONE);
		BOLTED_REDSTONE = block(ZingsOresAndTiersModBlocks.BOLTED_REDSTONE);
		SPECKLED_REDSTONE = block(ZingsOresAndTiersModBlocks.SPECKLED_REDSTONE);
		METALLIC_REDSTONE = block(ZingsOresAndTiersModBlocks.METALLIC_REDSTONE);
		GLOSSY_REDSTONE = block(ZingsOresAndTiersModBlocks.GLOSSY_REDSTONE);
		STONY_REDSTONE = block(ZingsOresAndTiersModBlocks.STONY_REDSTONE);
		CLUMPED_REDSTONE = block(ZingsOresAndTiersModBlocks.CLUMPED_REDSTONE);
		CLEAR_REDSTONE = block(ZingsOresAndTiersModBlocks.CLEAR_REDSTONE);
		CRYSTALIZED_REDSTONE = block(ZingsOresAndTiersModBlocks.CRYSTALIZED_REDSTONE);
		TOUGH_COPPER = block(ZingsOresAndTiersModBlocks.TOUGH_COPPER);
		BEVELED_COPPER = block(ZingsOresAndTiersModBlocks.BEVELED_COPPER);
		POWDERED_COPPER = block(ZingsOresAndTiersModBlocks.POWDERED_COPPER);
		SPECKLED_COPPER = block(ZingsOresAndTiersModBlocks.SPECKLED_COPPER);
		METALLIC_COPPER = block(ZingsOresAndTiersModBlocks.METALLIC_COPPER);
		GLOSSY_COPPER = block(ZingsOresAndTiersModBlocks.GLOSSY_COPPER);
		STONY_COPPER = block(ZingsOresAndTiersModBlocks.STONY_COPPER);
		CLUMPED_COPPER = block(ZingsOresAndTiersModBlocks.CLUMPED_COPPER);
		CLEAR_COPPER = block(ZingsOresAndTiersModBlocks.CLEAR_COPPER);
		CRYSTALIZED_COPPER = block(ZingsOresAndTiersModBlocks.CRYSTALIZED_COPPER);
		TOUGH_IRON = block(ZingsOresAndTiersModBlocks.TOUGH_IRON);
		BEVELED_IRON = block(ZingsOresAndTiersModBlocks.BEVELED_IRON);
		POWDERED_IRON = block(ZingsOresAndTiersModBlocks.POWDERED_IRON);
		SPECKLED_IRON = block(ZingsOresAndTiersModBlocks.SPECKLED_IRON);
		GLOSSY_IRON = block(ZingsOresAndTiersModBlocks.GLOSSY_IRON);
		STONY_IRON = block(ZingsOresAndTiersModBlocks.STONY_IRON);
		CLUMPED_IRON = block(ZingsOresAndTiersModBlocks.CLUMPED_IRON);
		CLEAR_IRON = block(ZingsOresAndTiersModBlocks.CLEAR_IRON);
		CRYSTALIZED_IRON = block(ZingsOresAndTiersModBlocks.CRYSTALIZED_IRON);
		METALLIC_NETHERITE = block(ZingsOresAndTiersModBlocks.METALLIC_NETHERITE);
		BEVELED_NETHERITE = block(ZingsOresAndTiersModBlocks.BEVELED_NETHERITE);
		POWDERED_NETHERITE = block(ZingsOresAndTiersModBlocks.POWDERED_NETHERITE);
		SPECKLED_NETHERITE = block(ZingsOresAndTiersModBlocks.SPECKLED_NETHERITE);
		GLOSSY_NETHERITE = block(ZingsOresAndTiersModBlocks.GLOSSY_NETHERITE);
		STONY_NETHERITE = block(ZingsOresAndTiersModBlocks.STONY_NETHERITE);
		CLUMPED_NETHERITE = block(ZingsOresAndTiersModBlocks.CLUMPED_NETHERITE);
		CLEAR_NETHERITE = block(ZingsOresAndTiersModBlocks.CLEAR_NETHERITE);
		CRYSTALIZED_NETHERITE = block(ZingsOresAndTiersModBlocks.CRYSTALIZED_NETHERITE);
		TOUGH_DIAMOND = block(ZingsOresAndTiersModBlocks.TOUGH_DIAMOND);
		METALLIC_DIAMOND = block(ZingsOresAndTiersModBlocks.METALLIC_DIAMOND);
		BEVELED_DIAMOND = block(ZingsOresAndTiersModBlocks.BEVELED_DIAMOND);
		POWDERED_DIAMOND = block(ZingsOresAndTiersModBlocks.POWDERED_DIAMOND);
		SPECKLED_DIAMOND = block(ZingsOresAndTiersModBlocks.SPECKLED_DIAMOND);
		BOLTED_DIAMOND = block(ZingsOresAndTiersModBlocks.BOLTED_DIAMOND);
		STONY_DIAMOND = block(ZingsOresAndTiersModBlocks.STONY_DIAMOND);
		CLUMPED_DIAMOND = block(ZingsOresAndTiersModBlocks.CLUMPED_DIAMOND);
		CLEAR_DIAMOND = block(ZingsOresAndTiersModBlocks.CLEAR_DIAMOND);
		CRYSTALIZED_DIAMOND = block(ZingsOresAndTiersModBlocks.CRYSTALIZED_DIAMOND);
		FLESH_IRON = register("flesh_iron", FleshIronItem::new);
		CRYSTAL_IRON = register("crystal_iron", CrystalIronItem::new);
		ROCK_IRON = register("rock_iron", RockIronItem::new);
		CLUMP_IRON = register("clump_iron", ClumpIronItem::new);
		SHARD_IRON = register("shard_iron", ShardIronItem::new);
		DUST_IRON = register("dust_iron", DustIronItem::new);
		HEX_IRON = register("hex_iron", HexIronItem::new);
		GEM_IRON = register("gem_iron", GemIronItem::new);
		GLOSSY_INGOT_IRON = register("glossy_ingot_iron", GlossyIngotIronItem::new);
		ROUGH_INGOT_IRON = register("rough_ingot_iron", RoughIngotIronItem::new);
		SHINY_INGOT_IRON = register("shiny_ingot_iron", ShinyIngotIronItem::new);
		FLESH_DIAMOND = register("flesh_diamond", FleshDiamondItem::new);
		CRYSTAL_DIAMOND = register("crystal_diamond", CrystalDiamondItem::new);
		ROCK_DIAMOND = register("rock_diamond", RockDiamondItem::new);
		CLUMP_DIAMOND = register("clump_diamond", ClumpDiamondItem::new);
		SHARD_DIAMOND = register("shard_diamond", ShardDiamondItem::new);
		DUST_DIAMOND = register("dust_diamond", DustDiamondItem::new);
		HEX_DIAMOND = register("hex_diamond", HexDiamondItem::new);
		CLEAR_INGOT_DIAMOND = register("clear_ingot_diamond", ClearIngotDiamondItem::new);
		GLOSSY_INGOT_DIAMOND = register("glossy_ingot_diamond", GlossyIngotDiamondItem::new);
		ROUGH_INGOT_DIAMOND = register("rough_ingot_diamond", RoughIngotDiamondItem::new);
		SHINY_INGOT_DIAMOND = register("shiny_ingot_diamond", ShinyIngotDiamondItem::new);
		CLEAR_INGOT_NETHERITE = register("clear_ingot_netherite", ClearIngotNetheriteItem::new);
		FLESH_NETHERITE = register("flesh_netherite", FleshNetheriteItem::new);
		CRYSTAL_NETHERITE = register("crystal_netherite", CrystalNetheriteItem::new);
		ROCK_NETHERITE = register("rock_netherite", RockNetheriteItem::new);
		CLUMP_NETHERITE = register("clump_netherite", ClumpNetheriteItem::new);
		SHARD_NETHERITE = register("shard_netherite", ShardNetheriteItem::new);
		DUST_NETHERITE = register("dust_netherite", DustNetheriteItem::new);
		HEX_NETHERITE = register("hex_netherite", HexNetheriteItem::new);
		GLOSSY_INGOT_NETHERITE = register("glossy_ingot_netherite", GlossyIngotNetheriteItem::new);
		GEM_NETHERITE = register("gem_netherite", GemNetheriteItem::new);
		SHINY_INGOT_NETHERITE = register("shiny_ingot_netherite", ShinyIngotNetheriteItem::new);
		CLEAR_INGOT_COPPER = register("clear_ingot_copper", ClearIngotCopperItem::new);
		FLESH_COPPER = register("flesh_copper", FleshCopperItem::new);
		CRYSTAL_COPPER = register("crystal_copper", CrystalCopperItem::new);
		ROCK_COPPER = register("rock_copper", RockCopperItem::new);
		CLUMP_COPPER = register("clump_copper", ClumpCopperItem::new);
		SHARD_COPPER = register("shard_copper", ShardCopperItem::new);
		DUST_COPPER = register("dust_copper", DustCopperItem::new);
		HEX_COPPER = register("hex_copper", HexCopperItem::new);
		ROUGH_INGOT_COPPER = register("rough_ingot_copper", RoughIngotCopperItem::new);
		GEM_COPPER = register("gem_copper", GemCopperItem::new);
		SHINY_INGOT_COPPER = register("shiny_ingot_copper", ShinyIngotCopperItem::new);
		CLEAR_INGOT_REDSTONE = register("clear_ingot_redstone", ClearIngotRedstoneItem::new);
		FLESH_REDSTONE = register("flesh_redstone", FleshRedstoneItem::new);
		CRYSTAL_REDSTONE = register("crystal_redstone", CrystalRedstoneItem::new);
		ROCK_REDSTONE = register("rock_redstone", RockRedstoneItem::new);
		CLUMP_REDSTONE = register("clump_redstone", ClumpRedstoneItem::new);
		SHARD_REDSTONE = register("shard_redstone", ShardRedstoneItem::new);
		GLOSSY_INGOT_REDSTONE = register("glossy_ingot_redstone", GlossyIngotRedstoneItem::new);
		HEX_REDSTONE = register("hex_redstone", HexRedstoneItem::new);
		ROUGH_INGOT_REDSTONE = register("rough_ingot_redstone", RoughIngotRedstoneItem::new);
		GEM_REDSTONE = register("gem_redstone", GemRedstoneItem::new);
		SHINY_INGOT_REDSTONE = register("shiny_ingot_redstone", ShinyIngotRedstoneItem::new);
		CLEAR_INGOT_LAPIS_LAZULI = register("clear_ingot_lapis_lazuli", ClearIngotLapisLazuliItem::new);
		DUST_LAPIS_LAZULI = register("dust_lapis_lazuli", DustLapisLazuliItem::new);
		CRYSTAL_LAPIS_LAZULI = register("crystal_lapis_lazuli", CrystalLapisLazuliItem::new);
		ROCK_LAPIS_LAZULI = register("rock_lapis_lazuli", RockLapisLazuliItem::new);
		CLUMP_LAPIS_LAZULI = register("clump_lapis_lazuli", ClumpLapisLazuliItem::new);
		SHARD_LAPIS_LAZULI = register("shard_lapis_lazuli", ShardLapisLazuliItem::new);
		GLOSSY_INGOT_LAPIS_LAZULI = register("glossy_ingot_lapis_lazuli", GlossyIngotLapisLazuliItem::new);
		HEX_LAPIS_LAZULI = register("hex_lapis_lazuli", HexLapisLazuliItem::new);
		ROUGH_INGOT_LAPIS_LAZULI = register("rough_ingot_lapis_lazuli", RoughIngotLapisLazuliItem::new);
		GEM_LAPIS_LAZULI = register("gem_lapis_lazuli", GemLapisLazuliItem::new);
		SHINY_INGOT_LAPIS_LAZULI = register("shiny_ingot_lapis_lazuli", ShinyIngotLapisLazuliItem::new);
		CLEAR_INGOT_COAL = register("clear_ingot_coal", ClearIngotCoalItem::new);
		DUST_COAL = register("dust_coal", DustCoalItem::new);
		CRYSTAL_COAL = register("crystal_coal", CrystalCoalItem::new);
		FLESH_COAL = register("flesh_coal", FleshCoalItem::new);
		CLUMP_COAL = register("clump_coal", ClumpCoalItem::new);
		SHARD_COAL = register("shard_coal", ShardCoalItem::new);
		GLOSSY_INGOT_COAL = register("glossy_ingot_coal", GlossyIngotCoalItem::new);
		HEX_COAL = register("hex_coal", HexCoalItem::new);
		ROUGH_INGOT_COAL = register("rough_ingot_coal", RoughIngotCoalItem::new);
		GEM_COAL = register("gem_coal", GemCoalItem::new);
		SHINY_INGOT_COAL = register("shiny_ingot_coal", ShinyIngotCoalItem::new);
		CLEAR_INGOT_RESIN = register("clear_ingot_resin", ClearIngotResinItem::new);
		DUST_RESIN = register("dust_resin", DustResinItem::new);
		CRYSTAL_RESIN = register("crystal_resin", CrystalResinItem::new);
		FLESH_RESIN = register("flesh_resin", FleshResinItem::new);
		ROCK_RESIN = register("rock_resin", RockResinItem::new);
		SHARD_RESIN = register("shard_resin", ShardResinItem::new);
		GLOSSY_INGOT_RESIN = register("glossy_ingot_resin", GlossyIngotResinItem::new);
		HEX_RESIN = register("hex_resin", HexResinItem::new);
		ROUGH_INGOT_RESIN = register("rough_ingot_resin", RoughIngotResinItem::new);
		GEM_RESIN = register("gem_resin", GemResinItem::new);
		SHINY_INGOT_RESIN = register("shiny_ingot_resin", ShinyIngotResinItem::new);
		CLEAR_INGOT_QUARTZ = register("clear_ingot_quartz", ClearIngotQuartzItem::new);
		DUST_QUARTZ = register("dust_quartz", DustQuartzItem::new);
		CLUMP_QUARTZ = register("clump_quartz", ClumpQuartzItem::new);
		FLESH_QUARTZ = register("flesh_quartz", FleshQuartzItem::new);
		ROCK_QUARTZ = register("rock_quartz", RockQuartzItem::new);
		SHARD_QUARTZ = register("shard_quartz", ShardQuartzItem::new);
		GLOSSY_INGOT_QUARTZ = register("glossy_ingot_quartz", GlossyIngotQuartzItem::new);
		HEX_QUARTZ = register("hex_quartz", HexQuartzItem::new);
		ROUGH_INGOT_QUARTZ = register("rough_ingot_quartz", RoughIngotQuartzItem::new);
		GEM_QUARTZ = register("gem_quartz", GemQuartzItem::new);
		SHINY_INGOT_QUARTZ = register("shiny_ingot_quartz", ShinyIngotQuartzItem::new);
		CLEAR_INGOT_AMETHYST = register("clear_ingot_amethyst", ClearIngotAmethystItem::new);
		DUST_AMETHYST = register("dust_amethyst", DustAmethystItem::new);
		CLUMP_AMETHYST = register("clump_amethyst", ClumpAmethystItem::new);
		FLESH_AMETHYST = register("flesh_amethyst", FleshAmethystItem::new);
		ROCK_AMETHYST = register("rock_amethyst", RockAmethystItem::new);
		CRYSTAL_AMETHYST = register("crystal_amethyst", CrystalAmethystItem::new);
		GLOSSY_INGOT_AMETHYST = register("glossy_ingot_amethyst", GlossyIngotAmethystItem::new);
		HEX_AMETHYST = register("hex_amethyst", HexAmethystItem::new);
		ROUGH_INGOT_AMETHYST = register("rough_ingot_amethyst", RoughIngotAmethystItem::new);
		GEM_AMETHYST = register("gem_amethyst", GemAmethystItem::new);
		SHINY_INGOT_AMETHYST = register("shiny_ingot_amethyst", ShinyIngotAmethystItem::new);
		CLEAR_INGOT_EMERALD = register("clear_ingot_emerald", ClearIngotEmeraldItem::new);
		DUST_EMERALD = register("dust_emerald", DustEmeraldItem::new);
		CLUMP_EMERALD = register("clump_emerald", ClumpEmeraldItem::new);
		FLESH_EMERALD = register("flesh_emerald", FleshEmeraldItem::new);
		ROCK_EMERALD = register("rock_emerald", RockEmeraldItem::new);
		CRYSTAL_EMERALD = register("crystal_emerald", CrystalEmeraldItem::new);
		GLOSSY_INGOT_EMERALD = register("glossy_ingot_emerald", GlossyIngotEmeraldItem::new);
		SHARD_EMERALD = register("shard_emerald", ShardEmeraldItem::new);
		ROUGH_INGOT_EMERALD = register("rough_ingot_emerald", RoughIngotEmeraldItem::new);
		GEM_EMERALD = register("gem_emerald", GemEmeraldItem::new);
		SHINY_INGOT_EMERALD = register("shiny_ingot_emerald", ShinyIngotEmeraldItem::new);
		CLEAR_INGOT_GOLD = register("clear_ingot_gold", ClearIngotGoldItem::new);
		DUST_GOLD = register("dust_gold", DustGoldItem::new);
		CLUMP_GOLD = register("clump_gold", ClumpGoldItem::new);
		FLESH_GOLD = register("flesh_gold", FleshGoldItem::new);
		ROCK_GOLD = register("rock_gold", RockGoldItem::new);
		CRYSTAL_GOLD = register("crystal_gold", CrystalGoldItem::new);
		GLOSSY_INGOT_GOLD = register("glossy_ingot_gold", GlossyIngotGoldItem::new);
		SHARD_GOLD = register("shard_gold", ShardGoldItem::new);
		ROUGH_INGOT_GOLD = register("rough_ingot_gold", RoughIngotGoldItem::new);
		GEM_GOLD = register("gem_gold", GemGoldItem::new);
		HEX_GOLD = register("hex_gold", HexGoldItem::new);
		RAW_NETHERITE = register("raw_netherite", RawNetheriteItem::new);
		BASALT_NETHERITE_ORE = block(ZingsOresAndTiersModBlocks.BASALT_NETHERITE_ORE, new Item.Properties().fireResistant());
		BONE_BLOCK_NETHERITE_ORE = block(ZingsOresAndTiersModBlocks.BONE_BLOCK_NETHERITE_ORE, new Item.Properties().fireResistant());
		NETHERITE_COMPASS = register("netherite_compass", NetheriteCompassItem::new);
		NETHERITE_CLOCK = register("netherite_clock", NetheriteClockItem::new);
		GOLDEN_UPGRADE = register("golden_upgrade", GoldenUpgradeItem::new);
		GOLDEN_COMPASS = register("golden_compass", GoldenCompassItem::new);
		COPPER_UPGRADE = register("copper_upgrade", CopperUpgradeItem::new);
		IRON_UPGRADE = register("iron_upgrade", IronUpgradeItem::new);
		COPPER_COMPASS = register("copper_compass", CopperCompassItem::new);
		COPPER_CLOCK = register("copper_clock", CopperClockItem::new);
		IRON_CLOCK = register("iron_clock", IronClockItem::new);
		COPPER_CAMPFIRE = block(ZingsOresAndTiersModBlocks.COPPER_CAMPFIRE);
		COPPER_NAME_TAG = register("copper_name_tag", CopperNameTagItem::new);
		GOLDEN_NAME_TAG = register("golden_name_tag", GoldenNameTagItem::new);
		NETHERITE_NAME_TAG = register("netherite_name_tag", NetheriteNameTagItem::new);
		PRISMARINE_ORE = block(ZingsOresAndTiersModBlocks.PRISMARINE_ORE);
		DEEPSLATE_PRISMARINE_ORE = block(ZingsOresAndTiersModBlocks.DEEPSLATE_PRISMARINE_ORE);
		BEVELED_PRISMARINE = block(ZingsOresAndTiersModBlocks.BEVELED_PRISMARINE);
		CLUMPED_PRISMARINE = block(ZingsOresAndTiersModBlocks.CLUMPED_PRISMARINE);
		CLEAR_PRISMARINE = block(ZingsOresAndTiersModBlocks.CLEAR_PRISMARINE);
		CRYSTALIZED_PRISMARINE = block(ZingsOresAndTiersModBlocks.CRYSTALIZED_PRISMARINE);
		BOLTED_PRISMARINE = block(ZingsOresAndTiersModBlocks.BOLTED_PRISMARINE);
		STONY_PRISMARINE = block(ZingsOresAndTiersModBlocks.STONY_PRISMARINE);
		ROUGH_PRISMARINE = block(ZingsOresAndTiersModBlocks.ROUGH_PRISMARINE);
		METALLIC_PRISMARINE = block(ZingsOresAndTiersModBlocks.METALLIC_PRISMARINE);
		GLOSSY_PRISMARINE = block(ZingsOresAndTiersModBlocks.GLOSSY_PRISMARINE);
		POWDERED_PRISMARINE = block(ZingsOresAndTiersModBlocks.POWDERED_PRISMARINE);
		SPECKLED_PRISMARINE = block(ZingsOresAndTiersModBlocks.SPECKLED_PRISMARINE);
		CLEAR_INGOT_PRISMARINE = register("clear_ingot_prismarine", ClearIngotPrismarineItem::new);
		SHINY_INGOT_PRISMARINE = register("shiny_ingot_prismarine", ShinyIngotPrismarineItem::new);
		GLOSSY_INGOT_PRISMARINE = register("glossy_ingot_prismarine", GlossyIngotPrismarineItem::new);
		ROUGH_INGOT_PRISMARINE = register("rough_ingot_prismarine", RoughIngotPrismarineItem::new);
		DUST_PRISMARINE = register("dust_prismarine", DustPrismarineItem::new);
		CLUMP_PRISMARINE = register("clump_prismarine", ClumpPrismarineItem::new);
		FLESH_PRISMARINE = register("flesh_prismarine", FleshPrismarineItem::new);
		ROCK_PRISMARINE = register("rock_prismarine", RockPrismarineItem::new);
		CRYSTAL_PRISMARINE = register("crystal_prismarine", CrystalPrismarineItem::new);
		SHARD_PRISMARINE = register("shard_prismarine", ShardPrismarineItem::new);
		GEM_PRISMARINE = register("gem_prismarine", GemPrismarineItem::new);
		HEX_PRISMARINE = register("hex_prismarine", HexPrismarineItem::new);
		GLASS_AMETHYST = register("glass_amethyst", GlassAmethystItem::new);
		GLASS_COAL = register("glass_coal", GlassCoalItem::new);
		GLASS_COPPER = register("glass_copper", GlassCopperItem::new);
		GLASS_DIAMOND = register("glass_diamond", GlassDiamondItem::new);
		GLASS_EMERALD = register("glass_emerald", GlassEmeraldItem::new);
		GLASS_GOLD = register("glass_gold", GlassGoldItem::new);
		GLASS_IRON = register("glass_iron", GlassIronItem::new);
		GLASS_LAPIS_LAZULI = register("glass_lapis_lazuli", GlassLapisLazuliItem::new);
		GLASS_NETHERITE = register("glass_netherite", GlassNetheriteItem::new);
		GLASS_QUARTZ = register("glass_quartz", GlassQuartzItem::new);
		GLASS_REDSTONE = register("glass_redstone", GlassRedstoneItem::new);
		GLASS_RESIN = register("glass_resin", GlassResinItem::new);
		HUE_AMETHYST = block(ZingsOresAndTiersModBlocks.HUE_AMETHYST);
		HUE_COAL = block(ZingsOresAndTiersModBlocks.HUE_COAL);
		HUE_COPPER = block(ZingsOresAndTiersModBlocks.HUE_COPPER);
		HUE_DIAMOND = block(ZingsOresAndTiersModBlocks.HUE_DIAMOND);
		HUE_EMERALD = block(ZingsOresAndTiersModBlocks.HUE_EMERALD);
		HUE_GOLD = block(ZingsOresAndTiersModBlocks.HUE_GOLD);
		HUE_IRON = block(ZingsOresAndTiersModBlocks.HUE_IRON);
		HUE_LAPIS_LAZULI = block(ZingsOresAndTiersModBlocks.HUE_LAPIS_LAZULI);
		HUE_NETHERITE = block(ZingsOresAndTiersModBlocks.HUE_NETHERITE, new Item.Properties().fireResistant());
		HUE_QUARTZ = block(ZingsOresAndTiersModBlocks.HUE_QUARTZ);
		HUE_REDSTONE = block(ZingsOresAndTiersModBlocks.HUE_REDSTONE);
		HUE_RESIN = block(ZingsOresAndTiersModBlocks.HUE_RESIN);
		PRISMARINE_SWORD = register("prismarine_sword", PrismarineSwordItem::new);
		PRISMARINE_AXE = register("prismarine_axe", PrismarineAxeItem::new);
		PRISMARINE_PICKAXE = register("prismarine_pickaxe", PrismarinePickaxeItem::new);
		PRISMARINE_SHOVEL = register("prismarine_shovel", PrismarineShovelItem::new);
		PRISMARINE_HOE = register("prismarine_hoe", PrismarineHoeItem::new);
		PRISMARINE_HELMET = register("prismarine_helmet", PrismarineItem.Helmet::new);
		PRISMARINE_CHESTPLATE = register("prismarine_chestplate", PrismarineItem.Chestplate::new);
		PRISMARINE_LEGGINGS = register("prismarine_leggings", PrismarineItem.Leggings::new);
		PRISMARINE_BOOTS = register("prismarine_boots", PrismarineItem.Boots::new);
		MYSTERY_ORE = block(ZingsOresAndTiersModBlocks.MYSTERY_ORE);
		DEEPSLATE_MYSTERY_ORE = block(ZingsOresAndTiersModBlocks.DEEPSLATE_MYSTERY_ORE);
		ORES_AND_TIERS_ICON = register("ores_and_tiers_icon", OresAndTiersIconItem::new);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static <I extends Item> DeferredItem<I> register(String name, Function<Item.Properties, ? extends I> supplier) {
		return REGISTRY.registerItem(name, supplier, Item.Properties::new);
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new BlockItem(block.get(), prop), () -> properties);
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block) {
		return doubleBlock(block, new Item.Properties());
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new DoubleHighBlockItem(block.get(), prop), () -> properties);
	}
}